/// <reference types="node" />
/**
 * Purpose: Verify App behavior with regression-focused unit tests.
 */

import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

const appSource = readFileSync(resolve(process.cwd(), 'src/App.tsx'), 'utf8')
const inspectorPanelSource = readFileSync(resolve(process.cwd(), 'src/components/inspector/InspectorPanel.tsx'), 'utf8')
const palettePanelSource = readFileSync(resolve(process.cwd(), 'src/components/palette/PalettePanel.tsx'), 'utf8')
const windowUiConfigSource = readFileSync(resolve(process.cwd(), 'src/windowing/windowUiConfig.ts'), 'utf8')

describe('App source regressions', () => {
  it('starts with dock and workbench hidden by default', () => {
    expect(appSource).toContain('const createDefaultWindowLayoutBootstrap = (topbarHeight: number): WindowLayoutBootstrap => ({')
    expect(appSource).toContain('dockCollapsed: true')
    expect(appSource).toContain('drawerCollapsed: true')
    expect(appSource).toContain('const [dockCollapsed, setDockCollapsed] = useState(windowLayoutBootstrap.dockCollapsed)')
    expect(appSource).toContain('const [drawerCollapsed, setDrawerCollapsed] = useState(windowLayoutBootstrap.drawerCollapsed)')
  })

  it('routes touch-first devices into a dedicated mobile shell and keeps timeline/dsl opening on the right', () => {
    expect(appSource).toContain("const [appShellMode, setAppShellMode] = useState<AppShellMode>(() => resolveInitialAppShellMode())")
    expect(appSource).toContain("const mobileDockTabLabel: Record<DockTab, string> = {")
    expect(appSource).toContain("timeline: 'Steps'")
    expect(appSource).toContain("preferences: 'Prefs'")
    expect(appSource).toContain("window.location.pathname === '/'")
    expect(appSource).toContain("window.history.replaceState(window.history.state, '', buildMobileShellPath(window.location.search, window.location.hash))")
    expect(appSource).toContain('if (appShellMode === \'mobile\') {')
    expect(appSource).toContain('className="mobile-shell-frame"')
    expect(appSource).toContain('role="tablist" aria-label="Mobile panels"')
    expect(appSource).toContain('className="mobile-topbar-meta"')
    expect(appSource).toContain('className="mobile-panel-heading"')
    expect(windowUiConfigSource).toContain("timeline: 'right'")
    expect(windowUiConfigSource).toContain("dsl: 'right'")
  })

  it('supports a dedicated shared export route that exposes only one media item', () => {
    expect(appSource).toContain("isSharedSupabaseAssetViewerLocation")
    expect(appSource).toContain("resolveSharedSupabaseAssetViewFromLocation")
    expect(appSource).toContain("buildSharedSupabaseAssetViewerUrl")
    expect(appSource).toContain("const isSharedSupabaseAssetRoute =")
    expect(appSource).toContain("if (isSharedSupabaseAssetRoute) {")
    expect(appSource).toContain("Shared SJV Export")
    expect(appSource).toContain("This clean viewer exposes only this exported file. It does not reveal the sender&apos;s full cloud library.")
    expect(appSource).toContain("Open media file")
    expect(appSource).toContain("Open Full App")
    expect(appSource).toContain("Shared export unavailable")
  })

  it('reopens managed panels in their remembered dock host and keeps the bottom workbench opt-in', () => {
    expect(appSource).toContain('resolveManagedDockPlacementForPanelOpen')
    expect(appSource).toContain('const drawerCollapsedBeforePresentationRef = useRef(true)')
    expect(appSource).toContain('setDrawerCollapsed(drawerCollapsedBeforePresentationRef.current)')
    expect((appSource.match(/setDrawerCollapsed\(false\)/g) ?? [])).toHaveLength(2)
  })

  it('measures topbar height from in-flow content instead of overflow popovers', () => {
    expect(appSource).toContain('const inFlowTopbarContentHeight = Array.from(topbarElement.children).reduce')
    expect(appSource).toContain("if (childPosition === 'absolute' || childPosition === 'fixed')")
    expect(appSource).toContain('contentHeight: inFlowTopbarContentHeight')
    expect(appSource).not.toContain('scrollHeight: topbarElement.scrollHeight')
  })

  it('persists UI density and applies a root density class', () => {
    expect(appSource).toContain("type UiDensity = 'comfortable' | 'compact'")
    expect(appSource).toContain("density: 'compact'")
    expect(appSource).toContain("parsed.density === 'compact' || parsed.density === 'comfortable'")
    expect(appSource).toContain('UI density')
    expect(appSource).toContain('UI Density: Compact')
    expect(appSource).toContain('app-layout-density-${uiPreferences.density}')
  })

  it('persists and wires a node depth-effects preference into the canvas renderer', () => {
    expect(appSource).toContain('nodeDepthEffectsEnabled: true')
    expect(appSource).toContain('parsed.nodeDepthEffectsEnabled ?? DEFAULT_UI_PREFERENCES.nodeDepthEffectsEnabled')
    expect(appSource).toContain('Enable node depth effects (3D look)')
    expect(appSource).toContain('Disable Node Depth Effects')
    expect(appSource).toContain('const nodeDepthEffectsActive =')
    expect(appSource).toContain('nodeDepthEffectsEnabled={nodeDepthEffectsActive}')
  })

  it('wires command palette, minimap, and performance mode into the app shell', () => {
    expect(appSource).toContain("import { CommandPalette } from './components/chrome/CommandPalette'")
    expect(appSource).toContain("import type { CommandPaletteItem } from './commandPalette/commandPalette'")
    expect(appSource).toContain("import {")
    expect(appSource).toContain('resolveMinimapModel')
    expect(appSource).toContain('resolveMinimapWorldPoint')
    expect(appSource).toContain('performanceModeEnabled: false')
    expect(appSource).toContain('minimapEnabled: true')
    expect(appSource).toContain('parsed.performanceModeEnabled ?? DEFAULT_UI_PREFERENCES.performanceModeEnabled')
    expect(appSource).toContain('parsed.minimapEnabled ?? DEFAULT_UI_PREFERENCES.minimapEnabled')
    expect(appSource).toContain('Show canvas minimap')
    expect(appSource).toContain('Performance mode')
    expect(appSource).toContain("key === 'k'")
    expect(appSource).toContain("event.key === '/'")
    expect(appSource).toContain('<CommandPalette')
    expect(appSource).toContain('className="command-palette-trigger"')
    expect(appSource).toContain('const commandPaletteItems: CommandPaletteActionItem[] = commandPaletteOpen ? (() =>')
    expect(appSource).toContain('section: \'Nodes\'')
    expect(appSource).toContain('section: \'Edges\'')
    expect(appSource).toContain('className="canvas-minimap"')
    expect(appSource).toContain('className="canvas-status-strip"')
    expect(appSource).toContain('uiPreferences.performanceModeEnabled ? \'app-layout-performance\' : \'\'')
    expect(appSource).toContain('!playerConfettiNonce || uiPreferences.performanceModeEnabled')
  })

  it('includes manual Supabase auth plus workspace, script, and gallery actions', () => {
    expect(appSource).toContain("supabaseCloudConfigured")
    expect(appSource).toContain("workspaceCloudProviderLabel")
    expect(appSource).toContain("workspaceCloudDatabaseUrl")
    expect(appSource).toContain("buildSupabaseCloudLibrarySections")
    expect(appSource).toContain("isSupabaseGalleryAssetShareable")
    expect(appSource).toContain('Open ${CLOUD_PROVIDER_LABEL} panel')
    expect(appSource).toContain('Use the top-right cloud badge for quick sign-in, gallery access, and automatic upload after standard PNG/GIF/MP4 exports.')
    expect(appSource).toContain('Standard PNG/GIF/MP4 exports now auto-upload here after the local file is generated.')
    expect(appSource).toContain('Your private ${CLOUD_PROVIDER_LABEL} library is live below. Saved scripts are grouped beside your uploaded assets.')
    expect(appSource).toContain('Refresh Library')
    expect(appSource).toContain('Workspace Snapshot')
    expect(appSource).toContain('Delete script from ${CLOUD_PROVIDER_LABEL}')
    expect(appSource).toContain('Saved cloud scripts')
    expect(appSource).toContain('Filter scripts')
    expect(appSource).toContain('Search by title or workspace id')
    expect(appSource).toContain('Showing ${filteredSupabaseCloudScripts.length} of ${supabaseCloudScripts.length} saved scripts.')
    expect(appSource).toContain('No saved scripts match this filter.')
    expect(appSource).toContain('No cloud library items yet.')
    expect(appSource).toContain('Save script')
    expect(appSource).toContain('Load script')
    expect(appSource).toContain('Load Saved SJV Script opens the clickable script list in the top-right cloud panel.')
    expect(appSource).toContain('Open gallery')
    expect(appSource).toContain('Upload local')
    expect(appSource).toContain('Only MP4 and GIF gallery exports can be shared right now.')
    expect(appSource).toContain('Share link')
    expect(appSource).toContain('Shared export link copied to clipboard.')
    expect(appSource).toContain('Shared export viewer opened in a new tab.')
    expect(appSource).not.toContain('Export PNG to Gallery')
    expect(appSource).not.toContain('Export GIF to Gallery')
    expect(appSource).not.toContain('Export MP4 to Gallery')
    expect(appSource).toContain('PNG exported and auto-uploaded to ${CLOUD_STATUS_LABEL} gallery.')
    expect(appSource).toContain('Animated GIF exported and auto-uploaded to ${CLOUD_STATUS_LABEL} gallery.')
    expect(appSource).toContain('MP4 exported and auto-uploaded to ${CLOUD_STATUS_LABEL} gallery.')
    expect(appSource).toContain('Sign In')
    expect(appSource).toContain('Save Workspace to Cloud')
    expect(appSource).toContain('Load Workspace from Cloud')
    expect(appSource).toContain('Save Generated SJV Script')
    expect(appSource).toContain('Load Saved SJV Script')
    expect(appSource).toContain('Upload File to Gallery')
    expect(appSource).toContain('Refresh Gallery List')
    expect(appSource).toContain('Save to ${CLOUD_PROVIDER_LABEL}')
    expect(appSource).toContain('Load from ${CLOUD_PROVIDER_LABEL}')
    expect(appSource).toContain('Save Script to ${CLOUD_PROVIDER_LABEL}')
    expect(appSource).toContain('Load Script from ${CLOUD_PROVIDER_LABEL}')
    expect(appSource).not.toContain('window.prompt(buildSupabaseCloudScriptSelectionPrompt')
    expect(appSource).toContain('Upload Media to ${CLOUD_PROVIDER_LABEL}')
    expect(appSource).not.toContain('Export PNG to Supabase Gallery')
    expect(appSource).not.toContain('Export GIF to Supabase Gallery')
    expect(appSource).not.toContain('Export MP4 to Supabase Gallery')
  })

  it('preserves in-memory visual edge state during live DSL sync imports', () => {
    expect(appSource).toContain("import { preserveWorkspaceVisualStateForDslSync } from './dsl-lite/preserveVisualState'")
    expect(appSource).toContain('const dslSyncWorkspaceRef = useRef(workspace)')
    expect(appSource).toContain('preserveWorkspaceVisualStateForDslSync(imported.workspace, dslSyncWorkspaceRef.current)')
    expect(appSource).toContain('preserveWorkspaceVisualStateForDslSync(imported.workspace, workspace)')
  })

  it('uses reusable collapsible panel groups across dock content', () => {
    expect(appSource).toContain("import { PanelGroup } from './components/chrome/PanelGroup'")
    expect(appSource).toContain("import { InspectorPanel } from './components/inspector/InspectorPanel'")
    expect(appSource).toContain("import { PalettePanel, type PalettePanelCategory } from './components/palette/PalettePanel'")
    expect(appSource).toContain('<PanelGroup title="Creation" defaultExpanded={false} className="journey-side-group">')
    expect(appSource).toContain('<PanelGroup title="Journeys" defaultExpanded className="journey-side-group">')
    expect(appSource).toContain('<PanelGroup title={CLOUD_PROVIDER_LABEL} defaultExpanded={false}>')
    expect(inspectorPanelSource).toContain('<PanelGroup title="Node details">')
    expect(palettePanelSource).toContain('defaultExpanded={index === 0}')
    expect(palettePanelSource).toContain('className="toolbox-group"')
  })

  it('keeps SJV Script panel free of Codex action buttons', () => {
    expect(appSource).not.toContain('Refine with Codex')
    expect(appSource).not.toContain('Clear Codex context')
    expect(appSource).not.toContain('requestCodexDslAssist')
  })

  it('renders Preferences using the reusable floating window component', () => {
    expect(appSource).toContain("import { FloatingWindow } from './components/windowing/FloatingWindow'")
    expect(appSource).toContain('<FloatingWindow')
    expect(appSource).toContain('MANAGED_WINDOW_FLOATING_UI_CONFIG[windowId]')
    expect(windowUiConfigSource).toContain("title: 'Preferences'")
    expect(windowUiConfigSource).toContain("className: 'preferences-window'")
  })

  it('renders managed docked windows through the reusable DockHost component', () => {
    expect(appSource).toContain("import { DockHost } from './components/windowing/DockHost'")
    expect(appSource).toContain('<DockHost')
    expect(appSource).toContain('renderManagedDockHostInDockPanel')
    expect(appSource).toContain('setManagedHostActiveTab')
  })

  it('renders floating managed windows through a shared loop and content mapper', () => {
    expect(appSource).toContain('MANAGED_WINDOW_IDS.filter')
    expect(appSource).toContain('floatingManagedWindows.map')
    expect(appSource).toContain('renderManagedWindowFloatingContent')
    expect(windowUiConfigSource).toContain("title: 'Palette'")
    expect(windowUiConfigSource).toContain("title: 'Journey Timeline'")
    expect(windowUiConfigSource).toContain("title: 'SJV Script'")
  })

  it('provides view menu actions to restore and reset managed window layout', () => {
    expect(appSource).toContain('const restoreWindowLayout = useCallback')
    expect(appSource).toContain('const resetWindowLayout = useCallback')
    expect(appSource).toContain('MANAGED_WINDOWS_LAYOUT_STORAGE_KEY')
    expect(appSource).toContain('Restore Window Layout')
    expect(appSource).toContain('Reset Window Layout')
  })

  it('includes a dedicated Window desktop menu for panel and layout actions', () => {
    expect(appSource).toContain("type DesktopMenuId = 'file' | 'edit' | 'view' | 'window'")
    expect(appSource).toContain("const DESKTOP_MENU_ORDER: DesktopMenuId[] = ['file', 'edit', 'view', 'window'")
    expect(appSource).toContain("aria-controls=\"desktop-menu-window\"")
    expect(appSource).toContain('aria-label="Window menu"')
    expect(appSource).toContain('Open Timeline Panel')
    expect(appSource).toContain('Open SJV Script Panel')
    expect(appSource).toContain('Open Preferences Panel')
    expect(appSource).toContain('Show Splash')
  })

  it('keeps Insert focused on showcase/tutorial content instead of window shortcuts', () => {
    expect(appSource).toContain('aria-label="Insert menu"')
    expect(appSource).toContain('Load Showcase (EN)')
    expect(appSource).toContain('Load Tutorial (PT)')
    expect(appSource).not.toContain('Open Journey Timeline')
    expect(appSource).not.toContain('Open SJV Script Editor')
    expect(appSource).not.toContain('Open Dock Panel')
  })

  it('includes a guided UI tutorial overlay and stable target hooks', () => {
    expect(appSource).toContain("import { SplashScreen } from './components/chrome/SplashScreen'")
    expect(appSource).toContain("import { GuidedTutorialOverlay } from './components/tutorial/GuidedTutorialOverlay'")
    expect(appSource).toContain('GUIDED_UI_TUTORIAL_STEPS')
    expect(appSource).toContain('resolveGuidedTutorialStepCompletion')
    expect(appSource).toContain('recordGuidedTutorialEvent')
    expect(appSource).toContain("'panel-shortcut-click'")
    expect(appSource).toContain("'toolbar-mode-click'")
    expect(appSource).toContain("'canvas-click'")
    expect(appSource).toContain("'window-menu-open-panel:inspector'")
    expect(appSource).toContain("'window-menu-open-panel:timeline'")
    expect(appSource).toContain("'window-menu-open-panel:dsl'")
    expect(appSource).toContain("'node-select'")
    expect(appSource).toContain("'edge-select'")
    expect(appSource).toContain("'inspector-node-name-edit'")
    expect(appSource).toContain("'inspector-edge-label-edit'")
    expect(appSource).toContain("'inspector-edge-protocol-edit'")
    expect(appSource).toContain("'dsl-sync-toggle'")
    expect(appSource).toContain('Start Guided Tutorial')
    expect(appSource).toContain('data-tutorial-id="main-menu-bar"')
    expect(appSource).toContain('data-tutorial-id="menu-window-trigger"')
    expect(appSource).toContain('data-tutorial-id="window-menu-open-inspector-panel"')
    expect(appSource).toContain('data-tutorial-id="window-menu-open-timeline-panel"')
    expect(appSource).toContain('data-tutorial-id="window-menu-open-dsl-panel"')
    expect(inspectorPanelSource).toContain('data-tutorial-id="inspector-node-name"')
    expect(inspectorPanelSource).toContain('data-tutorial-id="inspector-edge-label"')
    expect(inspectorPanelSource).toContain('data-tutorial-id="inspector-edge-protocol"')
    expect(appSource).toContain('data-tutorial-id="dsl-sync-toggle"')
    expect(appSource).toContain('data-tutorial-id="topbar-toolbar"')
    expect(appSource).toContain('data-tutorial-id="canvas-panel"')
    expect(appSource).toContain('data-tutorial-id="managed-host-bottom"')
    expect(appSource).toContain('<GuidedTutorialOverlay')
  })

  it('sanitizes help markdown comments before rendering the Guide tab', () => {
    expect(appSource).toContain('const SANITIZED_HELP_GUIDE_MARKDOWN = helpGuideMarkdown.replace(/<!--[\\s\\S]*?-->/g, \'\').trimStart()')
    expect(appSource).toContain('<ReactMarkdown>{SANITIZED_HELP_GUIDE_MARKDOWN}</ReactMarkdown>')
  })

  it('supports a presentation sequence-diagram surface with static export actions', () => {
    expect(appSource).toContain("type PresentationSurface = 'journey' | 'sequence'")
    expect(appSource).toContain("const [presentationSurface, setPresentationSurface] = useState<PresentationSurface>('journey')")
    expect(appSource).toContain("import { SequenceDiagramView } from './components/sequence/SequenceDiagramView'")
    expect(appSource).toContain("value={presentationSurface}")
    expect(appSource).toContain('Surface: Sequence diagram')
    expect(appSource).toContain('Export Sequence SVG')
    expect(appSource).toContain('Export Sequence PNG')
    expect(appSource).toContain('Export Sequence PDF')
    expect(appSource).toContain('<SequenceDiagramView scene={presentationSequenceScene} theme={theme} />')
    expect(appSource).toContain("document.querySelector(sequenceModeActive ? '.sequence-diagram-svg' : '.diagram-canvas')")
  })

  it('renders managed window hosts in dedicated left/right/bottom layout regions', () => {
    expect(appSource).toContain('managedLeftHostVisible')
    expect(appSource).toContain('managedRightHostVisible')
    expect(appSource).toContain('managedBottomHostVisible')
    expect(appSource).toContain("renderManagedDockHostPanel('left')")
    expect(appSource).toContain("renderManagedDockHostPanel('right')")
    expect(appSource).toContain("renderManagedDockHostPanel('bottom')")
    expect(appSource).toContain("'left managedLeft main managedRight right'")
    expect(appSource).toContain("'managedBottom managedBottom managedBottom managedBottom managedBottom'")
    expect(appSource).toContain('managedLeftHostWidth')
    expect(appSource).toContain('managedRightHostWidth')
    expect(appSource).toContain('managedBottomHostHeight')
    expect(appSource).toContain('layout-splitter-managed-left')
    expect(appSource).toContain('layout-splitter-managed-right')
    expect(appSource).toContain('layout-splitter-managed-bottom')
  })
})
