/// <reference types="node" />
/**
 * Purpose: Verify App behavior with regression-focused unit tests.
 */

import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

const appSource = readFileSync(resolve(process.cwd(), 'src/App.tsx'), 'utf8')
const inspectorPanelSource = readFileSync(resolve(process.cwd(), 'src/components/inspector/InspectorPanel.tsx'), 'utf8')
const palettePanelSource = readFileSync(resolve(process.cwd(), 'src/components/palette/PalettePanel.tsx'), 'utf8')
const uiPreferencesSource = readFileSync(resolve(process.cwd(), 'src/preferences/uiPreferences.ts'), 'utf8')
const iconRegistrySource = readFileSync(resolve(process.cwd(), 'src/icons/IconRegistry.tsx'), 'utf8')
const iconRegistryDataSource = readFileSync(resolve(process.cwd(), 'src/icons/iconRegistryData.ts'), 'utf8')
const windowUiConfigSource = readFileSync(resolve(process.cwd(), 'src/windowing/windowUiConfig.ts'), 'utf8')

describe('App source regressions', () => {
  it('starts with dock and workbench hidden by default', () => {
    expect(appSource).toContain('const createDefaultWindowLayoutBootstrap = (topbarHeight: number): WindowLayoutBootstrap => ({')
    expect(appSource).toContain('dockCollapsed: true')
    expect(appSource).toContain('drawerCollapsed: true')
    expect(appSource).toContain('const [dockCollapsed, setDockCollapsed] = useState(windowLayoutBootstrap.dockCollapsed)')
    expect(appSource).toContain('const [drawerCollapsed, setDrawerCollapsed] = useState(windowLayoutBootstrap.drawerCollapsed)')
  })

  it('routes touch-first devices into a dedicated mobile shell and keeps timeline/dsl opening on the right', () => {
    expect(appSource).toContain("const [appShellMode, setAppShellMode] = useState<AppShellMode>(() => resolveInitialAppShellMode())")
    expect(appSource).toContain("const mobileDockTabLabel: Record<DockTab, string> = {")
    expect(appSource).toContain("timeline: 'Steps'")
    expect(appSource).toContain("preferences: 'Prefs'")
    expect(appSource).toContain("window.location.pathname === '/'")
    expect(appSource).toContain("window.history.replaceState(window.history.state, '', buildMobileShellPath(window.location.search, window.location.hash))")
    expect(appSource).toContain('if (appShellMode === \'mobile\') {')
    expect(appSource).toContain('className="mobile-shell-frame"')
    expect(appSource).toContain('role="tablist" aria-label="Mobile panels"')
    expect(appSource).toContain('className="mobile-topbar-meta"')
    expect(appSource).toContain('className="mobile-panel-heading"')
    expect(windowUiConfigSource).toContain("timeline: 'right'")
    expect(windowUiConfigSource).toContain("dsl: 'right'")
  })

  it('supports a dedicated shared export route that exposes only one media item', () => {
    expect(appSource).toContain("isSharedSupabaseAssetViewerLocation")
    expect(appSource).toContain("resolveSharedSupabaseAssetViewFromLocation")
    expect(appSource).toContain("buildSharedSupabaseAssetViewerUrl")
    expect(appSource).toContain("const isSharedSupabaseAssetRoute =")
    expect(appSource).toContain("if (isSharedSupabaseAssetRoute) {")
    expect(appSource).toContain("Shared SJV Export")
    expect(appSource).toContain("This clean viewer exposes only this exported file. It does not reveal the sender&apos;s full cloud library.")
    expect(appSource).toContain("Open media file")
    expect(appSource).toContain("Open Full App")
    expect(appSource).toContain("Shared export unavailable")
  })

  it('reopens managed panels in their remembered dock host and keeps the bottom workbench opt-in', () => {
    expect(appSource).toContain('resolveManagedDockPlacementForPanelOpen')
    expect(appSource).toContain('const drawerCollapsedBeforePresentationRef = useRef(true)')
    expect(appSource).toContain('setDrawerCollapsed(drawerCollapsedBeforePresentationRef.current)')
    expect((appSource.match(/setDrawerCollapsed\(false\)/g) ?? [])).toHaveLength(2)
  })

  it('measures topbar height from in-flow content instead of overflow popovers', () => {
    expect(appSource).toContain('const inFlowTopbarContentHeight = Array.from(topbarElement.children).reduce')
    expect(appSource).toContain("if (childPosition === 'absolute' || childPosition === 'fixed')")
    expect(appSource).toContain('contentHeight: inFlowTopbarContentHeight')
    expect(appSource).not.toContain('scrollHeight: topbarElement.scrollHeight')
  })

  it('persists UI density and applies a root density class', () => {
    expect(uiPreferencesSource).toContain("export type UiDensity = 'comfortable' | 'compact'")
    expect(uiPreferencesSource).toContain("density: 'compact'")
    expect(uiPreferencesSource).toContain("candidate.density === 'compact' || candidate.density === 'comfortable'")
    expect(appSource).toContain('UI density')
    expect(appSource).toContain('UI Density: Compact')
    expect(appSource).toContain('app-layout-density-${uiPreferences.density}')
  })

  it('persists UI font scale, chrome theme presets, custom colors, and icon sets', () => {
    expect(uiPreferencesSource).toContain("export type UiFontScale = 'small' | 'normal' | 'large'")
    expect(uiPreferencesSource).toContain("export type ChromeThemeId = 'midnight' | 'graphite' | 'teal' | 'custom'")
    expect(uiPreferencesSource).toContain('CHROME_THEME_PRESETS')
    expect(uiPreferencesSource).toContain("chromeThemeId: 'midnight'")
    expect(uiPreferencesSource).toContain("fontScale: 'normal'")
    expect(uiPreferencesSource).toContain("canvasBackgroundPresetId: 'soft-grid'")
    expect(uiPreferencesSource).toContain("customCanvasBackground: DEFAULT_CUSTOM_CANVAS_BACKGROUND")
    expect(uiPreferencesSource).toContain("iconSet: 'lucide'")
    expect(uiPreferencesSource).toContain('menuBarVisible: true')
    expect(uiPreferencesSource).toContain('toolbarInlineWithBrand: false')
    expect(uiPreferencesSource).toContain('resolveUiPreferenceCssVariables')
    expect(appSource).toContain('UI font size')
    expect(appSource).toContain('Icon set')
    expect(appSource).toContain('Custom chrome colors')
    expect(appSource).toContain('Canvas color')
    expect(appSource).toContain('Reset canvas color')
    expect(appSource).toContain('Show main menu')
    expect(appSource).toContain('Place toolbar beside app icon')
    expect(appSource).toContain('app-layout-font-${uiPreferences.fontScale}')
    expect(appSource).toContain('app-chrome-theme-${uiPreferences.chromeThemeId}')
    expect(appSource).toContain('app-icon-set-${uiPreferences.iconSet}')
    expect(appSource).toContain("uiPreferences.menuBarVisible ? 'app-menu-visible' : 'app-menu-hidden'")
    expect(appSource).toContain('const compactInlineTopbar = !presentationMode && !uiPreferences.menuBarVisible')
    expect(appSource).toContain('const topbarToolbarInline = compactInlineTopbar || uiPreferences.toolbarInlineWithBrand')
    expect(appSource).toContain("topbarToolbarInline ? 'app-toolbar-inline' : 'app-toolbar-stacked'")
    expect(appSource).toContain("id: 'command:toggle-main-menu'")
    expect(appSource).toContain("id: 'command:toggle-inline-toolbar'")
    expect(appSource).toContain("id: 'command:open-cloud-panel'")
    expect(appSource).toContain('className="app-logo-badge app-logo-button"')
    expect(appSource).toContain('menuBarVisible: !current.menuBarVisible')
    expect(appSource).toContain('topbar-cloud-shell topbar-cloud-shell-floating')
    expect(appSource).not.toContain('compactInlineTopbar ? null : cloudBadgeControl')
    expect(appSource).toContain('{!presentationMode ? cloudPanelControl : null}')
    expect(appSource).toContain('topbar-dock-placement-strip')
    expect(appSource).not.toContain('className="topbar-dock-strip dock-tab-strip"')
    const utilityStripIndex = appSource.indexOf('className="topbar-utility-strip"')
    expect(utilityStripIndex).toBeGreaterThan(0)
    expect(appSource.slice(Math.max(0, utilityStripIndex - 120), utilityStripIndex)).toContain(
      '!presentationMode ? (',
    )
    expect(appSource).not.toContain('topbar-menu-restore-button')
    expect(appSource).toContain('style={appLayoutStyle}')
  })

  it('centralizes visible shell and palette icons behind a registry', () => {
    expect(iconRegistrySource).toContain('export const AppIcon')
    expect(iconRegistrySource).toContain('export const PresetIcon')
    expect(iconRegistryDataSource).toContain('APP_ICON_COMPONENTS')
    expect(iconRegistryDataSource).toContain('PRESET_ICON_COMPONENTS')
    expect(appSource).toContain("import { AppIcon, PresetIcon } from './icons/IconRegistry'")
    expect(appSource).toContain("import { TechIconGlyph } from './icons/TechIconGlyph'")
    expect(appSource).toContain('TECH_ICON_DRAG_MIME_TYPE')
    expect(appSource).toContain("import type { AppIconId } from './icons/iconRegistryData'")
    expect(appSource).toContain('const renderAppIcon = useCallback')
    expect(appSource).toContain('const MIXED_PALETTE_CATEGORIES = [')
    expect(appSource).toContain('renderPresetIcon={(preset) =>')
    expect(appSource).toContain('preset.dragMimeType === TECH_ICON_DRAG_MIME_TYPE')
    expect(appSource).toContain('<TechIconGlyph iconId={preset.id} size={18} className="palette-tech-icon-glyph" />')
    expect(appSource).toContain('<PresetIcon iconKey={preset.iconKey} iconSet={uiPreferences.iconSet} size={16} />')
    expect(appSource).toContain("palette: renderAppIcon('panel-left-open')")
    expect(appSource).toContain("icon: renderAppIcon('panel-left-open', 12)")
    expect(appSource).toContain("{renderAppIcon('pointer', 16)}")
  })

  it('persists and wires a node depth-effects preference into the canvas renderer', () => {
    expect(uiPreferencesSource).toContain('nodeDepthEffectsEnabled: false')
    expect(uiPreferencesSource).toContain('candidate.nodeDepthEffectsEnabled')
    expect(uiPreferencesSource).toContain('DEFAULT_UI_PREFERENCES.nodeDepthEffectsEnabled')
    expect(appSource).toContain('Enable node depth effects (3D look)')
    expect(appSource).toContain('Disable Node Depth Effects')
    expect(appSource).toContain('const nodeDepthEffectsActive =')
    expect(appSource).toContain('nodeDepthEffectsEnabled={nodeDepthEffectsActive}')
  })

  it('wires visible toolbar shortcut keys into the primary editing tools', () => {
    expect(appSource).toContain('const onToolShortcut = (event: KeyboardEvent) => {')
    expect(appSource).toContain("setActiveTool(key === 'v' ? 'select' : 'connector')")
    expect(appSource).toContain('<kbd className="toolbar-button-shortcut">V</kbd>')
    expect(appSource).toContain('<kbd className="toolbar-button-shortcut">C</kbd>')
  })

  it('wires command palette, minimap, and performance mode into the app shell', () => {
    expect(appSource).toContain("import { CommandPalette } from './components/chrome/CommandPalette'")
    expect(appSource).toContain("import type { CommandPaletteItem } from './commandPalette/commandPalette'")
    expect(appSource).toContain("import {")
    expect(appSource).toContain('resolveMinimapModel')
    expect(appSource).toContain('resolveMinimapWorldPoint')
    expect(uiPreferencesSource).toContain('performanceModeEnabled: false')
    expect(uiPreferencesSource).toContain('minimapEnabled: true')
    expect(uiPreferencesSource).toContain('statusBarEnabled: true')
    expect(uiPreferencesSource).toContain('DEFAULT_UI_PREFERENCES.performanceModeEnabled')
    expect(uiPreferencesSource).toContain('DEFAULT_UI_PREFERENCES.minimapEnabled')
    expect(uiPreferencesSource).toContain('DEFAULT_UI_PREFERENCES.statusBarEnabled')
    expect(appSource).toContain('Show canvas minimap')
    expect(appSource).toContain('Show status bar')
    expect(appSource).toContain('Performance mode')
    expect(appSource).toContain("key === 'k'")
    expect(appSource).toContain("event.key === '/'")
    expect(appSource).toContain('<CommandPalette')
    expect(appSource).toContain('className="command-palette-trigger"')
    expect(appSource).toContain('const commandPaletteItems: CommandPaletteActionItem[] = commandPaletteOpen ? (() =>')
    expect(appSource).toContain('section: \'Nodes\'')
    expect(appSource).toContain('section: \'Edges\'')
    expect(appSource).toContain('className="canvas-minimap"')
    expect(appSource).toContain("import { StatusBar, type StatusBarAction, type StatusBarItem } from './components/chrome/StatusBar'")
    expect(appSource).toContain('<StatusBar items={statusBarItems} actions={statusBarActions} />')
    expect(appSource).toContain('command:toggle-status-bar')
    expect(appSource).toContain('aria-label="Hide minimap"')
    expect(appSource).toContain('statusBarHeight + journeyHeight - 3')
    expect(appSource).toContain('uiPreferences.performanceModeEnabled ? \'app-layout-performance\' : \'\'')
    expect(appSource).toContain('!playerConfettiNonce || uiPreferences.performanceModeEnabled')
  })

  it('uses the app-native confirmation dialog instead of browser confirms', () => {
    expect(appSource).toContain("import { ConfirmationDialog, type ConfirmationDialogTone } from './components/chrome/ConfirmationDialog'")
    expect(appSource).toContain('type ConfirmationDialogState = {')
    expect(appSource).toContain('const requestConfirmation = useCallback')
    expect(appSource).toContain('const confirmationDialogControl = (')
    expect(appSource).toContain('<ConfirmationDialog')
    expect(appSource).toContain('Delete selected nodes?')
    expect(appSource).toContain('Delete edge?')
    expect(appSource).not.toContain('window.confirm')
  })

  it('includes manual Supabase auth plus workspace, script, and gallery actions', () => {
    expect(appSource).toContain("supabaseCloudConfigured")
    expect(appSource).toContain("workspaceCloudProviderLabel")
    expect(appSource).toContain("workspaceCloudDatabaseUrl")
    expect(appSource).toContain("buildSupabaseCloudLibrarySections")
    expect(appSource).toContain("isSupabaseGalleryAssetShareable")
    expect(appSource).toContain("DEFAULT_SHOWCASE_LIBRARY_SECTIONS")
    expect(appSource).toContain("DEFAULT_SHOWCASE_SCRIPTS")
    expect(appSource).toContain("DEFAULT_SHOWCASE_ANIMATIONS")
    expect(appSource).toContain('Open ${CLOUD_PROVIDER_LABEL} Panel')
    expect(appSource).toContain('Use this panel for sign-in, gallery access, and automatic upload after standard PNG/GIF/MP4 exports.')
    expect(appSource).toContain('Standard PNG/GIF/MP4 exports now auto-upload here after the local file is generated.')
    expect(appSource).toContain('Your private ${CLOUD_PROVIDER_LABEL} library is live below. Saved scripts are grouped beside your uploaded assets.')
    expect(appSource).toContain('Sample showcase scripts and animated exports are always available below.')
    expect(appSource).toContain('Seed Sample Library')
    expect(appSource).toContain('Sample showcase library saved to your provider library.')
    expect(appSource).toContain('Refresh Library')
    expect(appSource).toContain('Workspace Snapshot')
    expect(appSource).toContain('Delete script from ${CLOUD_PROVIDER_LABEL}')
    expect(appSource).toContain('Saved cloud scripts')
    expect(appSource).toContain('Filter scripts')
    expect(appSource).toContain('Search by title or workspace id')
    expect(appSource).toContain('Showing ${filteredSupabaseCloudScripts.length} of ${supabaseCloudScripts.length} saved scripts.')
    expect(appSource).toContain('No saved scripts match this filter.')
    expect(appSource).toContain('No private library items yet.')
    expect(appSource).toContain('Save script')
    expect(appSource).toContain('Load script')
    expect(appSource).toContain('Load Saved SJV Script opens the clickable script list in the cloud panel.')
    expect(appSource).toContain('Open gallery')
    expect(appSource).toContain('Upload local')
    expect(appSource).toContain('Only MP4 and GIF gallery exports can be shared right now.')
    expect(appSource).toContain('Share link')
    expect(appSource).toContain('Shared export link copied to clipboard.')
    expect(appSource).toContain('Shared export viewer opened in a new tab.')
    expect(appSource).not.toContain('Export PNG to Gallery')
    expect(appSource).not.toContain('Export GIF to Gallery')
    expect(appSource).not.toContain('Export MP4 to Gallery')
    expect(appSource).toContain('PNG exported and auto-uploaded to ${CLOUD_STATUS_LABEL} gallery.')
    expect(appSource).toContain('Animated GIF exported and auto-uploaded to ${CLOUD_STATUS_LABEL} gallery.')
    expect(appSource).toContain('MP4 exported and auto-uploaded to ${CLOUD_STATUS_LABEL} gallery.')
    expect(appSource).toContain('Sign In')
    expect(appSource).toContain('Save Workspace to Cloud')
    expect(appSource).toContain('Load Workspace from Cloud')
    expect(appSource).toContain('Save Generated SJV Script')
    expect(appSource).toContain('Load Saved SJV Script')
    expect(appSource).toContain('Upload File to Gallery')
    expect(appSource).toContain('Refresh Gallery List')
    expect(appSource).toContain('Save to ${CLOUD_PROVIDER_LABEL}')
    expect(appSource).toContain('Load from ${CLOUD_PROVIDER_LABEL}')
    expect(appSource).toContain('Save Script to ${CLOUD_PROVIDER_LABEL}')
    expect(appSource).toContain('Load Script from ${CLOUD_PROVIDER_LABEL}')
    expect(appSource).not.toContain('window.prompt(buildSupabaseCloudScriptSelectionPrompt')
    expect(appSource).toContain('Upload Media to ${CLOUD_PROVIDER_LABEL}')
    expect(appSource).not.toContain('Export PNG to Supabase Gallery')
    expect(appSource).not.toContain('Export GIF to Supabase Gallery')
    expect(appSource).not.toContain('Export MP4 to Supabase Gallery')
  })

  it('wires experimental canvas shapes and custom context menus outside SJV Script', () => {
    expect(appSource).toContain('BASIC_SHAPE_DEFINITIONS')
    expect(appSource).toContain('addBasicShape')
    expect(appSource).toContain('addExperimentalShapeToCanvas')
    expect(appSource).toContain('setActiveTool(shape.kind)')
    expect(appSource).toContain('Drag on the canvas to draw a ${shape.label.toLowerCase()} shape.')
    expect(appSource).toContain('canvas-context-menu')
    expect(appSource).toContain('handleAppContextMenu')
    expect(appSource).toContain('Experimental shapes stay out of SJV Script and journeys.')
    expect(appSource).toContain('Light theme is under construction')
    expect(appSource).toContain('applyWorkspaceTheme')
  })

  it('preserves in-memory visual edge state during live DSL sync imports', () => {
    expect(appSource).toContain("import { preserveWorkspaceVisualStateForDslSync } from './dsl-lite/preserveVisualState'")
    expect(appSource).toContain('const dslSyncWorkspaceRef = useRef(workspace)')
    expect(appSource).toContain('preserveWorkspaceVisualStateForDslSync(imported.workspace, dslSyncWorkspaceRef.current)')
    expect(appSource).toContain('preserveWorkspaceVisualStateForDslSync(imported.workspace, workspace)')
  })

  it('uses reusable collapsible panel groups across dock content', () => {
    expect(appSource).toContain("import { PanelGroup } from './components/chrome/PanelGroup'")
    expect(appSource).toContain("import { InspectorPanel } from './components/inspector/InspectorPanel'")
    expect(appSource).toContain("import { PalettePanel, type PalettePanelCategory } from './components/palette/PalettePanel'")
    expect(appSource).toContain('<PanelGroup title="Creation" defaultExpanded={false} className="journey-side-group">')
    expect(appSource).toContain('<PanelGroup title="Journeys" defaultExpanded className="journey-side-group">')
    expect(appSource).toContain('<PanelGroup title={CLOUD_PROVIDER_LABEL} defaultExpanded={false}>')
    expect(inspectorPanelSource).toContain('<PanelGroup title="Node details">')
    expect(palettePanelSource).toContain('className="palette-browser"')
    expect(palettePanelSource).toContain('Search palette components')
    expect(palettePanelSource).toContain('className="palette-category-overflow"')
    expect(palettePanelSource).toContain('contentClassName="palette-category-strip"')
    expect(palettePanelSource).toContain('collapseNavWhenHidden')
  })

  it('wires timeline thread indent and outdent actions through the store', () => {
    expect(appSource).toContain('const indentJourneyStepToThread = useEditorStore((state) => state.indentJourneyStepToThread)')
    expect(appSource).toContain('const outdentJourneyThreadStep = useEditorStore((state) => state.outdentJourneyThreadStep)')
    expect(appSource).toContain('const onJourneyStepIndent = useCallback')
    expect(appSource).toContain('const onJourneyThreadStepOutdent = useCallback')
    expect(appSource).toContain('onIndentStep={onJourneyStepIndent}')
    expect(appSource).toContain('onOutdentStep={onJourneyThreadStepOutdent}')
  })

  it('exposes node drilldown creation and navigation from UI actions', () => {
    expect(appSource).toContain('const openDrilldown = useEditorStore((state) => state.openDrilldown)')
    expect(appSource).toContain('const createDrilldownForNode = useEditorStore((state) => state.createDrilldownForNode)')
    expect(appSource).toContain('const runNodeDrilldownAction = useCallback')
    expect(appSource).toContain('node.kind === \'note\' || isExperimentalShapeNode(node)')
    expect(appSource).toContain('openDrilldown(nodeId)')
    expect(appSource).toContain('createDrilldownForNode(nodeId)')
    expect(appSource).toContain('onNodeDrilldown={runNodeDrilldownAction}')
    expect(appSource).toContain('resolveNodeDrilldownActionLabel(canvasContextMenu.nodeId)')
    expect(inspectorPanelSource).toContain('selectedNode.drilldownRef ? \'Open Drilldown\' : \'Create Drilldown\'')
  })

  it('keeps SJV Script panel free of Codex action buttons', () => {
    expect(appSource).not.toContain('Refine with Codex')
    expect(appSource).not.toContain('Clear Codex context')
    expect(appSource).not.toContain('requestCodexDslAssist')
  })

  it('renders Preferences using the reusable floating window component', () => {
    expect(appSource).toContain("import { FloatingWindow } from './components/windowing/FloatingWindow'")
    expect(appSource).toContain('<FloatingWindow')
    expect(appSource).toContain('MANAGED_WINDOW_FLOATING_UI_CONFIG[windowId]')
    expect(windowUiConfigSource).toContain("title: 'Preferences'")
    expect(windowUiConfigSource).toContain("className: 'preferences-window'")
  })

  it('renders managed docked windows through the reusable DockHost component', () => {
    expect(appSource).toContain("import { DockHost } from './components/windowing/DockHost'")
    expect(appSource).toContain('<DockHost')
    expect(appSource).toContain('renderManagedDockHostInDockPanel')
    expect(appSource).toContain('setManagedHostActiveTab')
    expect(appSource).toContain('onHeaderTearOff=')
    expect(appSource).toContain('floatManagedDockHostWindow(hostId, activeTabId)')
  })

  it('renders floating managed windows through a shared loop and content mapper', () => {
    expect(appSource).toContain('MANAGED_WINDOW_IDS.filter')
    expect(appSource).toContain('floatingManagedWindows.map')
    expect(appSource).toContain('renderManagedWindowFloatingContent')
    expect(windowUiConfigSource).toContain("title: 'Palette'")
    expect(windowUiConfigSource).toContain("title: 'Journey Timeline'")
    expect(windowUiConfigSource).toContain("title: 'SJV Script'")
  })

  it('provides view menu actions to restore and reset managed window layout', () => {
    expect(appSource).toContain('const restoreWindowLayout = useCallback')
    expect(appSource).toContain('const resetWindowLayout = useCallback')
    expect(appSource).toContain('MANAGED_WINDOWS_LAYOUT_STORAGE_KEY')
    expect(appSource).toContain('Restore Window Layout')
    expect(appSource).toContain('Reset Window Layout')
  })

  it('includes a dedicated Window desktop menu for panel and layout actions', () => {
    expect(appSource).toContain("type DesktopMenuId = 'file' | 'edit' | 'view' | 'window'")
    expect(appSource).toContain("const DESKTOP_MENU_ORDER: DesktopMenuId[] = ['file', 'edit', 'view', 'window'")
    expect(appSource).toContain("aria-controls=\"desktop-menu-window\"")
    expect(appSource).toContain('aria-label="Window menu"')
    expect(appSource).toContain('Open Timeline Panel')
    expect(appSource).toContain('Open SJV Script Panel')
    expect(appSource).toContain('Open Preferences Panel')
    expect(appSource).toContain('Show Splash')
  })

  it('keeps Insert focused on showcase/tutorial content instead of window shortcuts', () => {
    expect(appSource).toContain('aria-label="Insert menu"')
    expect(appSource).toContain('Load Showcase (EN)')
    expect(appSource).toContain('Load Tutorial (PT)')
    expect(appSource).not.toContain('Open Journey Timeline')
    expect(appSource).not.toContain('Open SJV Script Editor')
    expect(appSource).not.toContain('Open Dock Panel')
  })

  it('includes a guided UI tutorial overlay and stable target hooks', () => {
    expect(appSource).toContain("import { SplashScreen } from './components/chrome/SplashScreen'")
    expect(appSource).toContain("import { GuidedTutorialOverlay } from './components/tutorial/GuidedTutorialOverlay'")
    expect(appSource).toContain('GUIDED_UI_TUTORIAL_STEPS')
    expect(appSource).toContain('resolveGuidedTutorialStepCompletion')
    expect(appSource).toContain('recordGuidedTutorialEvent')
    expect(appSource).toContain('data-tutorial-id="panel-shortcuts-strip"')
    expect(appSource).toContain("'toolbar-mode-click'")
    expect(appSource).toContain("'canvas-click'")
    expect(appSource).toContain("'window-menu-open-panel:inspector'")
    expect(appSource).toContain("'window-menu-open-panel:timeline'")
    expect(appSource).toContain("'window-menu-open-panel:dsl'")
    expect(appSource).toContain("'node-select'")
    expect(appSource).toContain("'edge-select'")
    expect(appSource).toContain("'inspector-node-name-edit'")
    expect(appSource).toContain("'inspector-edge-label-edit'")
    expect(appSource).toContain("'inspector-edge-protocol-edit'")
    expect(appSource).toContain("'dsl-sync-toggle'")
    expect(appSource).toContain('Start Guided Tutorial')
    expect(appSource).toContain('data-tutorial-id="main-menu-bar"')
    expect(appSource).toContain('data-tutorial-id="menu-window-trigger"')
    expect(appSource).toContain('data-tutorial-id="window-menu-open-inspector-panel"')
    expect(appSource).toContain('data-tutorial-id="window-menu-open-timeline-panel"')
    expect(appSource).toContain('data-tutorial-id="window-menu-open-dsl-panel"')
    expect(inspectorPanelSource).toContain('data-tutorial-id="inspector-node-name"')
    expect(inspectorPanelSource).toContain('data-tutorial-id="inspector-edge-label"')
    expect(inspectorPanelSource).toContain('data-tutorial-id="inspector-edge-protocol"')
    expect(appSource).toContain('data-tutorial-id="dsl-sync-toggle"')
    expect(appSource).toContain('data-tutorial-id="topbar-toolbar"')
    expect(appSource).toContain('data-tutorial-id="canvas-panel"')
    expect(appSource).toContain('data-tutorial-id="managed-host-bottom"')
    expect(appSource).toContain('<GuidedTutorialOverlay')
  })

  it('sanitizes help markdown comments before rendering the Guide tab', () => {
    expect(appSource).toContain('const SANITIZED_HELP_GUIDE_MARKDOWN = helpGuideMarkdown.replace(/<!--[\\s\\S]*?-->/g, \'\').trimStart()')
    expect(appSource).toContain('<ReactMarkdown>{SANITIZED_HELP_GUIDE_MARKDOWN}</ReactMarkdown>')
  })

  it('supports a presentation sequence-diagram surface with static export actions', () => {
    expect(appSource).toContain("type PresentationSurface = 'journey' | 'sequence'")
    expect(appSource).toContain("const [presentationSurface, setPresentationSurface] = useState<PresentationSurface>('journey')")
    expect(appSource).toContain("import { SequenceDiagramView } from './components/sequence/SequenceDiagramView'")
    expect(appSource).toContain("value={presentationSurface}")
    expect(appSource).toContain('Surface: Sequence diagram')
    expect(appSource).toContain('Export Sequence SVG')
    expect(appSource).toContain('Export Sequence PNG')
    expect(appSource).toContain('Export Sequence PDF')
    expect(appSource).toContain('<SequenceDiagramView scene={presentationSequenceScene} theme={theme} />')
    expect(appSource).toContain("document.querySelector(sequenceModeActive ? '.sequence-diagram-svg' : '.diagram-canvas')")
  })

  it('renders managed window hosts in dedicated left/right/bottom layout regions', () => {
    expect(appSource).toContain('managedLeftHostVisible')
    expect(appSource).toContain('managedRightHostVisible')
    expect(appSource).toContain('managedBottomHostVisible')
    expect(appSource).toContain("renderManagedDockHostPanel('left')")
    expect(appSource).toContain("renderManagedDockHostPanel('right')")
    expect(appSource).toContain("renderManagedDockHostPanel('bottom')")
    expect(appSource).toContain("'left managedLeft main managedRight right'")
    expect(appSource).toContain("'managedBottom managedBottom managedBottom managedBottom managedBottom'")
    expect(appSource).toContain('managedLeftHostWidth')
    expect(appSource).toContain('managedRightHostWidth')
    expect(appSource).toContain('managedBottomHostHeight')
    expect(appSource).toContain('layout-splitter-managed-left')
    expect(appSource).toContain('layout-splitter-managed-right')
    expect(appSource).toContain('layout-splitter-managed-bottom')
  })

  it('renders a floating canvas tools rail with real editor actions', () => {
    expect(appSource).toContain('className="canvas-tools-rail"')
    expect(appSource).toContain('aria-label="Canvas tools"')
    expect(appSource).toContain('aria-label="Select tool"')
    expect(appSource).toContain('aria-label="Connector tool"')
    expect(appSource).toContain("openManagedDockedWindowFromDockTab('palette')")
    expect(appSource).toContain("openManagedDockedWindowFromDockTab('inspector')")
    expect(appSource).toContain("openManagedDockedWindowFromDockTab('dsl')")
    expect(appSource).toContain('onClick={() => openCommandPalette()}')
  })
})
