/// <reference types="node" />
/**
 * Purpose: Verify App.styles behavior with regression-focused unit tests.
 */

import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

const appCss = readFileSync(resolve(process.cwd(), 'src/App.css'), 'utf8')

describe('App boundary styles', () => {
  it('uses boundary border as the only pointer hit-area', () => {
    expect(appCss).toMatch(/\.node-boundary\s*\{[^}]*fill:\s*none;[^}]*pointer-events:\s*stroke;[^}]*\}/s)
    expect(appCss).toMatch(/\.theme-dark\s+\.node-boundary\s*\{[^}]*fill:\s*none;[^}]*\}/s)
  })

  it('styles mode pills and splitters for visual mode indication and resizing', () => {
    expect(appCss).toContain('.mode-pill')
    expect(appCss).toContain('.mode-pill-active')
    expect(appCss).toContain('.mode-pill-playing')
    expect(appCss).toContain('.topbar-status')
    expect(appCss).toContain('.app-layout-focus')
    expect(appCss).toContain('.app-layout-presentation')
    expect(appCss).toContain('.focus-toggle-button')
    expect(appCss).toContain('.icon-toggle-button')
    expect(appCss).toContain('.layout-splitter-left')
    expect(appCss).toContain('.layout-splitter-journey')
  })

  it('styles drawer tabs, dock panel and monaco dsl layout', () => {
    expect(appCss).toContain('.drawer-tabs')
    expect(appCss).toContain('.drawer-tab')
    expect(appCss).toContain('.drawer-maximize-button')
    expect(appCss).toContain('.journey-drawer-dsl .dsl-panel')
    expect(appCss).toContain('.journey-drawer-dock')
    expect(appCss).toContain('.dock-panel')
    expect(appCss).toContain('.dock-tab-body-dsl')
    expect(appCss).toContain('.dock-tab-strip')
    expect(appCss).toContain('.dock-tab')
    expect(appCss).toContain('.dock-tab-icon')
    expect(appCss).toContain('.dock-host')
    expect(appCss).toContain('.dock-host-header')
    expect(appCss).toContain('.dock-host-header-draggable')
    expect(appCss).toContain('.dock-host-strip')
    expect(appCss).toContain('.dock-host-actions-row')
    expect(appCss).toContain('.dock-host-tabs-row')
    expect(appCss).toContain('.dock-host-tabs-viewport')
    expect(appCss).toContain('.dock-host-scroll-controls')
    expect(appCss).toContain('.overflow-strip-nav')
    expect(appCss).toContain('.overflow-strip-nav-collapsed')
    expect(appCss).toContain('.overflow-strip-navs-collapsed')
    expect(appCss).toContain('.dock-host-tab')
    expect(appCss).toContain('.dock-host-body')
    expect(appCss).toContain('.managed-host-sidebar')
    expect(appCss).toContain('.managed-host-sidebar-left')
    expect(appCss).toContain('.managed-host-sidebar-right')
    expect(appCss).toContain('.managed-host-bottom')
    expect(appCss).toContain('.dock-panel-managed')
    expect(appCss).toContain('.dock-placement')
    expect(appCss).toContain('.journey-side-player')
    expect(appCss).toContain('.journey-side-group')
    expect(appCss).toContain('.journey-list-sidebar')
    expect(appCss).toContain('.journey-timeline-toolbar')
    expect(appCss).toContain('.journey-item-edge-drop-target')
    expect(appCss).toContain('.inspector-actions')
    expect(appCss).toContain('.edge-label-position-value')
    expect(appCss).toContain('.dsl-monaco-editor')
    expect(appCss).toContain('.dsl-panel-maximized .dsl-monaco-editor')
    expect(appCss).toContain('.dsl-status-message')
    expect(appCss).toContain('.floating-window')
    expect(appCss).toContain('.floating-window-close')
    expect(appCss).toContain('.floating-window-body-dock')
    expect(appCss).toContain('.floating-window-body-dsl')
    expect(appCss).toContain('.layout-splitter-managed-left')
    expect(appCss).toContain('.layout-splitter-managed-right')
    expect(appCss).toContain('.layout-splitter-managed-bottom')
  })

  it('includes flow animation for player feedback', () => {
    expect(appCss).toContain('.edge-flowing')
    expect(appCss).toContain('.edge-flowing-animated')
    expect(appCss).toContain('@keyframes edge-flow-dash')
    expect(appCss).toContain('@keyframes node-port-affordance-pulse')
    expect(appCss).not.toContain('.node-group-impact')
    expect(appCss).not.toContain('@keyframes node-impact-shake')
  })

  it('uses seamless dashed animation settings for edge flow', () => {
    expect(appCss).toMatch(/\.edge-flowing\s*\{[^}]*stroke-dasharray:\s*6 6;[^}]*\}/s)
    expect(appCss).toMatch(/\.edge-flowing-animated\s*\{[^}]*animation:\s*edge-flow-dash\s+0.9s\s+linear\s+infinite;[^}]*\}/s)
    expect(appCss).toContain('stroke-dashoffset: -12;')
  })

  it('contains visual styles for node shapes and color palette', () => {
    expect(appCss).toContain('.node-shape-detail')
    expect(appCss).toContain('.node-connector-icon')
    expect(appCss).toContain('.node-connector-female')
    expect(appCss).toContain('.node-connector-male')
    expect(appCss).toContain('.node-color-presets')
    expect(appCss).toContain('.node-color-chip')
    expect(appCss).toContain('.journey-drag-handle')
    expect(appCss).toContain('.node-journey-dimmed')
    expect(appCss).toContain('.edge-dimmed')
    expect(appCss).toContain('.edge-label-dimmed')
  })

  it('includes desktop menu and advanced canvas interaction styles', () => {
    expect(appCss).toMatch(/\.topbar\s*\{[^}]*overflow:\s*visible;[^}]*\}/s)
    expect(appCss).toContain('.app-layout-density-compact')
    expect(appCss).toContain('--sjv-density-topbar-gap')
    expect(appCss).toMatch(/\.topbar-meta\s*\{[^}]*grid-template-columns:\s*auto minmax\(0,\s*1fr\) auto;[^}]*\}/s)
    expect(appCss).toMatch(/\.app-brand-copy\s*\{[^}]*display:\s*none;[^}]*\}/s)
    expect(appCss).toMatch(/\.mode-indicators\s*\{[^}]*display:\s*none;[^}]*\}/s)
    expect(appCss).toContain('.desktop-menu-bar')
    expect(appCss).toMatch(
      /\.desktop-menu-bar\s*\{[^}]*flex-wrap:\s*wrap;[^}]*flex:\s*1 1 auto;[^}]*overflow:\s*visible;[^}]*\}/s,
    )
    expect(appCss).toMatch(
      /\.topbar-actions\s*\{[^}]*flex-wrap:\s*nowrap;[^}]*overflow-x:\s*auto;[^}]*overflow-y:\s*hidden;[^}]*\}/s,
    )
    expect(appCss).toContain('.toolbar-icon-button')
    expect(appCss).toMatch(
      /\.app-layout-presentation\s+\.topbar\s*\{[^}]*grid-template-columns:\s*auto minmax\(0,\s*1fr\);[^}]*\}/s,
    )
    expect(appCss).toContain('.topbar-cloud-shell')
    expect(appCss).toContain('.topbar-utility-strip')
    expect(appCss).toContain('.command-palette-trigger')
    expect(appCss).toContain('.app-logo-button')
    expect(appCss).toContain('.command-palette-backdrop')
    expect(appCss).toContain('.command-palette-row-active')
    expect(appCss).toContain('.topbar-cloud-badge')
    expect(appCss).not.toContain('.topbar-menu-restore-button')
    expect(appCss).toContain('.topbar-cloud-panel')
    expect(appCss).toContain('.topbar-cloud-field')
    expect(appCss).toContain('.topbar-cloud-command-grid')
    expect(appCss).toContain('.topbar-cloud-command-card')
    expect(appCss).toContain('.topbar-cloud-command-label')
    expect(appCss).toContain('.topbar-cloud-command-buttons')
    expect(appCss).toContain('.topbar-cloud-script-picker')
    expect(appCss).toContain('.topbar-cloud-script-search')
    expect(appCss).toContain('.topbar-cloud-script-search-label')
    expect(appCss).toContain('.topbar-cloud-script-summary')
    expect(appCss).toContain('.topbar-cloud-script-list')
    expect(appCss).toContain('.topbar-cloud-script-row-shell')
    expect(appCss).toContain('.topbar-cloud-script-row')
    expect(appCss).toContain('.topbar-cloud-script-row-chip')
    expect(appCss).toContain('.topbar-cloud-script-row-delete')
    expect(appCss).toContain('.topbar-cloud-script-row-active')
    expect(appCss).toContain('.topbar-cloud-script-row-badge')
    expect(appCss).toContain('.help-gallery-sections')
    expect(appCss).toContain('.help-gallery-provider-status')
    expect(appCss).toContain('.help-gallery-section')
    expect(appCss).toContain('.help-gallery-section-header')
    expect(appCss).toContain('.help-gallery-section-badge')
    expect(appCss).toContain('.help-gallery-script-preview')
    expect(appCss).toContain('.help-gallery-script-preview-badge')
    expect(appCss).toContain('.help-gallery-card-meta')
    expect(appCss).toContain('.help-gallery-icon-button')
    expect(appCss).toContain('.mobile-app')
    expect(appCss).toContain('.mobile-shell-frame')
    expect(appCss).toContain('.mobile-topbar')
    expect(appCss).toContain('.mobile-topbar-meta')
    expect(appCss).toContain('.mobile-meta-pill')
    expect(appCss).toContain('.mobile-panel-shell')
    expect(appCss).toContain('.mobile-panel-tab')
    expect(appCss).toContain('.mobile-panel-heading')
    expect(appCss).toContain('.mobile-toolbar-button')
    expect(appCss).toContain('.mobile-toolbar-button-compact')
    expect(appCss).toMatch(
      /\.app-layout-presentation\s+\.topbar-actions\s*\{[^}]*grid-column:\s*2;[^}]*grid-row:\s*1;[^}]*flex-wrap:\s*nowrap;[^}]*overflow-x:\s*auto;[^}]*\}/s,
    )
    expect(appCss).toContain('.desktop-menu-trigger')
    expect(appCss).toContain('.desktop-menu-open')
    expect(appCss).toContain('.app-logo-badge')
    expect(appCss).toContain('.desktop-menu-list')
    expect(appCss).toContain('.desktop-menu-item-icon')
    expect(appCss).toContain('.canvas-back-arrow')
    expect(appCss).toContain('.app-text')
    expect(appCss).toContain('.app-text-svg')
    expect(appCss).toContain('.app-text-inline-editor-control')
    expect(appCss).toContain('.app-status-bar')
    expect(appCss).toContain('.app-status-bar-item-primary')
    expect(appCss).toContain('.app-status-bar-icon')
    expect(appCss).toContain('.app-status-bar-button')
    expect(appCss).toContain('.app-status-bar-button-active')
    expect(appCss).toContain('.canvas-minimap')
    expect(appCss).toContain('.canvas-minimap-actions')
    expect(appCss).toContain('.canvas-minimap-viewport')
    expect(appCss).toContain('.canvas-tools-rail')
    expect(appCss).toContain('.canvas-tool-button-active')
    expect(appCss).toContain('.palette-browser')
    expect(appCss).toContain('.palette-search')
    expect(appCss).toContain('.palette-category-overflow')
    expect(appCss).toContain('.palette-category-viewport')
    expect(appCss).toContain('.palette-category-chip-active')
    expect(appCss).toContain('.palette-preset-card')
    expect(appCss).toContain('.canvas-alignment-guide')
    expect(appCss).toContain('.canvas-selection-marquee')
    expect(appCss).toContain('.node-border-hitarea')
    expect(appCss).toContain('.node-drilldown-hitarea')
    expect(appCss).toContain('.node-connection-target')
    expect(appCss).toContain('.node-port-affordance')
    expect(appCss).toContain('.node-port-highlight')
    expect(appCss).toContain('.edge-hitarea')
    expect(appCss).toContain('.edge-journey-dragging')
    expect(appCss).toContain('.diagram-canvas-depth-off .node-depth-layer')
    expect(appCss).toContain('.node-depth-fill')
    expect(appCss).toContain('.node-depth-rim')
    expect(appCss).toContain('.edge-anchor-handle')
    expect(appCss).toContain('.edge-anchor-handle-active')
    expect(appCss).toContain('.edge-label-draggable')
    expect(appCss).toContain('.edge-label-vertical')
    expect(appCss).toContain('.edge-selected-indicator')
    expect(appCss).toContain('.panel-group')
    expect(appCss).toContain('.panel-group-toggle')
    expect(appCss).toContain('.journey-filter-button')
    expect(appCss).toContain('.app-layout-performance')
  })

  it('keeps the workbench chrome compact and neutral for long editing sessions', () => {
    expect(appCss).toMatch(/:root\s*\{[^}]*--sjv-canvas-bg:\s*#eef1f5;/s)
    expect(appCss).toMatch(/\.theme-dark\s*\{[^}]*background:\s*#0b1220;[^}]*--sjv-canvas-bg:\s*#111827;/s)
    expect(appCss).toMatch(/--sjv-density-menu-trigger-radius:\s*4px;/)
    expect(appCss).toMatch(/--sjv-density-toolbar-button-radius:\s*5px;/)
    expect(appCss).toContain('.toolbar-group + .toolbar-group::before')
    expect(appCss).toMatch(/\.topbar-dock-strip\s*\{[^}]*border:\s*0;[^}]*border-left:\s*1px solid #cbd5e1;[^}]*background:\s*transparent;[^}]*box-shadow:\s*none;/s)
    expect(appCss).toMatch(/\.topbar-dock-strip\.dock-tab-strip\s*\{[^}]*padding:\s*0 0 0 10px;[^}]*overflow:\s*visible;[^}]*\}/s)
    expect(appCss).toMatch(/\.topbar-dock-strip\s+\.dock-tab-spacer\s*\{[^}]*display:\s*none;[^}]*\}/s)
    expect(appCss).toMatch(/\.toolbar-button-label\s*\{[^}]*display:\s*inline;[^}]*font-size:\s*12px;/s)
    expect(appCss).toContain('.toolbar-button-shortcut')
    expect(appCss).toContain('.palette-browser-title')
    expect(appCss).toMatch(/\.palette-category-chip\s*\{[^}]*font-weight:\s*500;[^}]*\}/s)
    expect(appCss).toMatch(/\.toolbox-item-label\s*\{[^}]*font-weight:\s*500;[^}]*\}/s)
    expect(appCss).toMatch(/\.managed-host-sidebar-left\s*\{[^}]*background:\s*#17212b;[^}]*border-right-color:\s*#263544;[^}]*\}/s)
    expect(appCss).toMatch(/\.managed-host-sidebar-left\s+\.palette-preset-grid\s*\{[^}]*grid-template-columns:\s*1fr;[^}]*\}/s)
    expect(appCss).toMatch(/\.canvas-tools-rail\s*\{[^}]*position:\s*absolute;[^}]*background:\s*#1d2a35;[^}]*\}/s)
    expect(appCss).toMatch(/\.node-depth-fill\s*\{[^}]*opacity:\s*0\.18;[^}]*\}/s)
  })

  it('supports polished chrome themes with UI font scale, custom colors, and light canvas', () => {
    expect(appCss).toContain('--sjv-ui-font-scale')
    expect(appCss).toContain('--sjv-shell-control-text')
    expect(appCss).toMatch(/\.app-text-size-sm\s*\{[^}]*font-size:\s*var\(--sjv-ui-font-sm,\s*12px\);/s)
    expect(appCss).toContain('.app-toolbar-inline.app-menu-hidden .topbar')
    expect(appCss).toContain('.preferences-theme-grid')
    expect(appCss).toContain('.preferences-theme-card-active')
    expect(appCss).toContain('.preferences-color-grid')
    expect(appCss).toContain('.preferences-color-control')
    expect(appCss).toMatch(/\.node-note-title\s*\{[^}]*font-weight:\s*400;[^}]*letter-spacing:\s*0;/s)
    expect(appCss).toContain('.app-chrome-theme-midnight')
    expect(appCss).toContain('.app-chrome-theme-graphite')
    expect(appCss).toContain('.app-chrome-theme-teal')
    expect(appCss).toContain('.app-chrome-theme-custom')
    expect(appCss).toMatch(/\.app-status-bar\s*\{[^}]*background:\s*#1d4ed8;/s)
    expect(appCss).toMatch(/\.app-chrome-theme-midnight, \.app-chrome-theme-graphite, \.app-chrome-theme-teal, \.app-chrome-theme-custom\)/)
    expect(appCss).toContain('background: var(--sjv-shell-status-bg);')
    expect(appCss).toMatch(/\.dock-host-body\s*\{[^}]*scrollbar-width:\s*none;/s)
    expect(appCss).toMatch(/\.palette-category-overflow\s*\{[^}]*grid-template-columns:\s*14px minmax\(0,\s*1fr\) 14px;/s)
    expect(appCss).toMatch(/:is\(\.app-chrome-theme-midnight,[^)]+\.app-chrome-theme-custom\)[\s\S]*\.canvas-panel[\s\S]*background:\s*#eef1f5;/)
  })

  it('styles the guided tutorial overlay and help guide actions', () => {
    expect(appCss).toMatch(/\.splash-screen\s*\{[^}]*pointer-events:\s*auto;[^}]*\}/s)
    expect(appCss).toContain('.splash-preview-chip')
    expect(appCss).toContain('.guided-tutorial-overlay')
    expect(appCss).toContain('.guided-tutorial-backdrop-pane')
    expect(appCss).toContain('.guided-tutorial-spotlight')
    expect(appCss).toMatch(/\.guided-tutorial-spotlight\s*\{[^}]*background:\s*transparent;[^}]*\}/s)
    expect(appCss).not.toContain('0 0 0 9999px rgba(2, 6, 23, 0.62)')
    expect(appCss).toContain('.guided-tutorial-card')
    expect(appCss).toContain('.guided-tutorial-actions')
    expect(appCss).toContain('.guided-tutorial-requirement')
    expect(appCss).toContain('.guided-tutorial-requirement-complete')
    expect(appCss).toContain('.guided-tutorial-primary-button')
    expect(appCss).toContain('.help-guide-actions')
    expect(appCss).toContain('.help-gallery-preview-empty')
    expect(appCss).toContain('.help-gallery-empty')
    expect(appCss).toContain('.help-gallery-card-actions')
    expect(appCss).toContain('.shared-asset-view')
    expect(appCss).toContain('.shared-asset-shell')
    expect(appCss).toContain('.shared-asset-media-frame')
    expect(appCss).toContain('.shared-asset-action-primary')
    expect(appCss).toContain('.theme-dark .help-guide-actions button')
  })

  it('applies the imported dark palette and arrow styling tokens', () => {
    expect(appCss).toContain('--sjv-canvas-bg')
    expect(appCss).toContain('--sjv-edge-player')
    expect(appCss).toContain('.edge-arrow-head')
    expect(appCss).toContain('.theme-dark .canvas-panel::before')
  })
})
