import type { WorkspaceModel } from './types'

const defaultPorts = [
  { id: 'north', x: 0.5, y: 0 },
  { id: 'east', x: 1, y: 0.5 },
  { id: 'south', x: 0.5, y: 1 },
  { id: 'west', x: 0, y: 0.5 },
]

export const createDefaultWorkspace = (): WorkspaceModel => ({
  schemaVersion: '1.0',
  workspace: {
    id: 'workspace-default',
    name: 'C4 Journey Workspace',
  },
  views: {
    v_container: {
      id: 'v_container',
      kind: 'container',
      name: 'Container View',
      nodeIds: ['n_api', 'n_kafka', 'n_db'],
      edgeIds: [],
      journeyIds: [],
    },
    v_components_api: {
      id: 'v_components_api',
      kind: 'component',
      name: 'ms-orders Components',
      nodeIds: ['n_comp_app', 'n_comp_domain', 'n_comp_adapter_out'],
      edgeIds: ['e_comp_1', 'e_comp_2'],
      journeyIds: [],
    },
  },
  nodes: {
    n_api: {
      id: 'n_api',
      presetId: 'container',
      kind: 'container',
      name: 'ms-orders',
      tags: ['core'],
      tech: { id: 'spring-boot', label: 'Spring Boot', iconKey: 'spring' },
      bounds: { x: 180, y: 120, w: 220, h: 120 },
      ports: defaultPorts,
      children: [],
      drilldownRef: 'v_components_api',
    },
    n_kafka: {
      id: 'n_kafka',
      presetId: 'queue',
      kind: 'queue',
      name: 'Kafka',
      tags: ['infra'],
      tech: { id: 'kafka', label: 'Kafka', iconKey: 'kafka' },
      bounds: { x: 520, y: 110, w: 180, h: 90 },
      ports: defaultPorts,
      children: [],
    },
    n_db: {
      id: 'n_db',
      presetId: 'db',
      kind: 'db',
      name: 'orders-db',
      tags: ['infra'],
      tech: { id: 'postgres', label: 'PostgreSQL', iconKey: 'postgres' },
      bounds: { x: 520, y: 260, w: 180, h: 90 },
      ports: defaultPorts,
      children: [],
    },
    n_comp_app: {
      id: 'n_comp_app',
      presetId: 'component',
      kind: 'component',
      name: 'OrderService',
      tags: ['component'],
      tech: { id: 'spring', label: 'Spring Component', iconKey: 'spring' },
      bounds: { x: 200, y: 120, w: 200, h: 100 },
      ports: defaultPorts,
      children: [],
    },
    n_comp_domain: {
      id: 'n_comp_domain',
      presetId: 'component',
      kind: 'component',
      name: 'OrderDomain',
      tags: ['component'],
      tech: { id: 'domain', label: 'Domain', iconKey: 'component' },
      bounds: { x: 470, y: 120, w: 200, h: 100 },
      ports: defaultPorts,
      children: [],
    },
    n_comp_adapter_out: {
      id: 'n_comp_adapter_out',
      presetId: 'component',
      kind: 'component',
      name: 'KafkaPublisher',
      tags: ['component'],
      tech: { id: 'kafka', label: 'Kafka Adapter', iconKey: 'kafka' },
      bounds: { x: 340, y: 290, w: 220, h: 100 },
      ports: defaultPorts,
      children: [],
    },
  },
  edges: {
    e_comp_1: {
      id: 'e_comp_1',
      from: { nodeId: 'n_comp_app' },
      to: { nodeId: 'n_comp_domain' },
      protocolPresetId: 'internal-call',
      label: 'validate()',
      route: { kind: 'auto', points: [] },
      style: { arrow: true, dashed: false, thickness: 2 },
    },
    e_comp_2: {
      id: 'e_comp_2',
      from: { nodeId: 'n_comp_app' },
      to: { nodeId: 'n_comp_adapter_out' },
      protocolPresetId: 'event',
      label: 'publish()',
      route: { kind: 'auto', points: [] },
      style: { arrow: true, dashed: false, thickness: 2 },
    },
  },
  journeys: {},
  settings: {
    grid: false,
    snap: false,
  },
})
