import type { WorkspaceModel } from './types'
import { normalizeWorkspaceNodePorts } from './nodePorts'

const defaultPorts = [
  { id: 'north', x: 0.5, y: 0 },
  { id: 'east', x: 1, y: 0.5 },
  { id: 'south', x: 0.5, y: 1 },
  { id: 'west', x: 0, y: 0.5 },
]

export const createDefaultWorkspace = (): WorkspaceModel =>
  normalizeWorkspaceNodePorts({
    schemaVersion: '1.0',
    workspace: {
      id: 'workspace-default',
      name: 'Orders Platform Showcase',
    },
    views: {
      v_container: {
        id: 'v_container',
        kind: 'container',
        name: 'Container View',
        nodeIds: [
          'n_frontend',
          'n_gateway',
          'n_auth',
          'n_api',
          'n_worker',
          'n_kafka',
          'n_db',
          'n_obs',
          'n_note_gateway',
          'n_note_projection',
          'n_note_tutorial',
        ],
        edgeIds: [
          'e_c_1',
          'e_c_2',
          'e_c_3',
          'e_c_4',
          'e_c_5',
          'e_c_6',
          'e_c_7',
          'e_c_8',
          'e_c_9',
          'e_c_10',
          'e_c_11',
        ],
        journeyIds: ['j_c_1', 'j_c_2', 'j_c_3'],
      },
      v_components_api: {
        id: 'v_components_api',
        kind: 'component',
        name: 'ms-orders Components',
        nodeIds: [
          'n_comp_controller',
          'n_comp_app',
          'n_comp_domain',
          'n_comp_repo',
          'n_comp_adapter_out',
          'n_comp_mapper',
          'n_note_component_guardrails',
        ],
        edgeIds: ['e_comp_1', 'e_comp_2', 'e_comp_3', 'e_comp_4', 'e_comp_5', 'e_comp_6'],
        journeyIds: ['j_comp_1'],
      },
      v_hex_api: {
        id: 'v_hex_api',
        kind: 'hex',
        name: 'ms-orders Hex View',
        nodeIds: [
          'n_hex_adapter_in',
          'n_hex_port_in',
          'n_hex_app_service',
          'n_hex_domain',
          'n_hex_port_out',
          'n_hex_adapter_out',
          'n_hex_obs',
          'n_note_hex_boundary',
        ],
        edgeIds: ['e_hex_1', 'e_hex_2', 'e_hex_3', 'e_hex_4', 'e_hex_5', 'e_hex_6'],
        journeyIds: ['j_hex_1'],
      },
      v_components_worker: {
        id: 'v_components_worker',
        kind: 'component',
        name: 'ms-fulfillment Components',
        nodeIds: [
          'n_worker_comp_consumer',
          'n_worker_comp_app',
          'n_worker_comp_projection_repo',
          'n_worker_comp_metric_publisher',
          'n_note_worker_flow',
        ],
        edgeIds: [
          'e_worker_comp_1',
          'e_worker_comp_2',
          'e_worker_comp_3',
          'e_worker_comp_4',
        ],
        journeyIds: ['j_worker_comp_1'],
      },
      v_hex_worker: {
        id: 'v_hex_worker',
        kind: 'hex',
        name: 'ms-fulfillment Hex View',
        nodeIds: [
          'n_worker_hex_adapter_in',
          'n_worker_hex_port_in',
          'n_worker_hex_app_service',
          'n_worker_hex_domain',
          'n_worker_hex_port_out',
          'n_worker_hex_adapter_out',
          'n_worker_hex_obs',
          'n_note_worker_hex',
        ],
        edgeIds: [
          'e_worker_hex_1',
          'e_worker_hex_2',
          'e_worker_hex_3',
          'e_worker_hex_4',
          'e_worker_hex_5',
          'e_worker_hex_6',
        ],
        journeyIds: ['j_worker_hex_1'],
      },
    },
    nodes: {
      n_frontend: {
        id: 'n_frontend',
        presetId: 'container',
        kind: 'container',
        name: 'web-portal',
        tags: ['entrypoint'],
        tech: { id: 'react', label: 'React', iconKey: 'component' },
        style: { fillColor: '#1e293b', textColor: '#f8fafc' },
        bounds: { x: 70, y: 110, w: 220, h: 120 },
        ports: defaultPorts,
        children: [],
      },
      n_gateway: {
        id: 'n_gateway',
        presetId: 'gateway',
        kind: 'gateway',
        name: 'api-gateway',
        tags: ['infra'],
        tech: { id: 'nginx', label: 'NGINX', iconKey: 'gateway' },
        style: { fillColor: '#b45309', textColor: '#fef3c7' },
        bounds: { x: 350, y: 110, w: 220, h: 110 },
        ports: defaultPorts,
        children: [],
      },
      n_auth: {
        id: 'n_auth',
        presetId: 'security',
        kind: 'security',
        name: 'auth-service',
        tags: ['security'],
        tech: { id: 'oauth2', label: 'OAuth2', iconKey: 'security' },
        style: { fillColor: '#7f1d1d', textColor: '#fee2e2' },
        bounds: { x: 350, y: 270, w: 220, h: 100 },
        ports: defaultPorts,
        children: [],
      },
      n_api: {
        id: 'n_api',
        presetId: 'container',
        kind: 'container',
        name: 'ms-orders',
        tags: ['core'],
        tech: { id: 'spring-boot', label: 'Spring Boot', iconKey: 'spring' },
        style: { fillColor: '#1d4ed8', textColor: '#f8fafc' },
        bounds: { x: 640, y: 110, w: 220, h: 120 },
        ports: defaultPorts,
        children: [],
        drilldownRef: 'v_components_api',
      },
      n_worker: {
        id: 'n_worker',
        presetId: 'container',
        kind: 'container',
        name: 'ms-fulfillment',
        tags: ['core'],
        tech: { id: 'spring-boot', label: 'Spring Boot', iconKey: 'spring' },
        style: { fillColor: '#0f766e', textColor: '#f0fdfa' },
        bounds: { x: 640, y: 280, w: 220, h: 120 },
        ports: defaultPorts,
        children: [],
        drilldownRef: 'v_components_worker',
      },
      n_kafka: {
        id: 'n_kafka',
        presetId: 'queue',
        kind: 'queue',
        name: 'Kafka',
        tags: ['infra'],
        tech: { id: 'kafka', label: 'Kafka', iconKey: 'kafka' },
        style: { fillColor: '#334155', textColor: '#f8fafc' },
        bounds: { x: 940, y: 100, w: 200, h: 100 },
        ports: defaultPorts,
        children: [],
      },
      n_db: {
        id: 'n_db',
        presetId: 'db',
        kind: 'db',
        name: 'orders-db',
        tags: ['infra'],
        tech: { id: 'postgres', label: 'PostgreSQL', iconKey: 'postgres' },
        style: { fillColor: '#1e293b', textColor: '#e2e8f0' },
        bounds: { x: 940, y: 250, w: 200, h: 100 },
        ports: defaultPorts,
        children: [],
      },
      n_obs: {
        id: 'n_obs',
        presetId: 'component',
        kind: 'component',
        name: 'telemetry',
        tags: ['observability'],
        tech: { id: 'observability', label: 'Observability', iconKey: 'search' },
        style: { fillColor: '#4338ca', textColor: '#e0e7ff' },
        bounds: { x: 940, y: 410, w: 200, h: 100 },
        ports: defaultPorts,
        children: [],
      },
      n_note_gateway: {
        id: 'n_note_gateway',
        presetId: 'note',
        kind: 'note',
        name: 'Gateway contract:\nvalidate_token before forwarding requests.',
        tags: ['note', 'showcase'],
        bounds: { x: 300, y: 18, w: 280, h: 112 },
        ports: [],
        children: [],
        noteTargetNodeId: 'n_gateway',
      },
      n_note_projection: {
        id: 'n_note_projection',
        presetId: 'note',
        kind: 'note',
        name: 'Projection pipeline:\norder.created -> worker -> read model update.',
        tags: ['note', 'showcase'],
        bounds: { x: 890, y: 500, w: 300, h: 112 },
        ports: [],
        children: [],
        noteTargetNodeId: 'n_worker',
      },
      n_note_tutorial: {
        id: 'n_note_tutorial',
        presetId: 'note',
        kind: 'note',
        name: 'Tutorial: open drilldown on each MS and play journeys.\nThen export GIF/MP4 from File menu.',
        tags: ['note', 'showcase', 'tutorial'],
        bounds: { x: 1110, y: 18, w: 360, h: 112 },
        ports: [],
        children: [],
        noteTargetNodeId: 'n_api',
      },
      n_comp_controller: {
        id: 'n_comp_controller',
        presetId: 'adapter-in',
        kind: 'adapter-in',
        name: 'OrdersController',
        tags: ['component'],
        tech: { id: 'adapter-in', label: 'REST Adapter', iconKey: 'gateway' },
        style: { fillColor: '#2563eb', textColor: '#eff6ff' },
        bounds: { x: 130, y: 140, w: 220, h: 110 },
        ports: defaultPorts,
        children: [],
      },
      n_comp_app: {
        id: 'n_comp_app',
        presetId: 'application-service',
        kind: 'application-service',
        name: 'CreateOrderService',
        tags: ['component'],
        tech: { id: 'application-service', label: 'Application Service', iconKey: 'component' },
        style: { fillColor: '#0891b2', textColor: '#ecfeff' },
        bounds: { x: 430, y: 130, w: 250, h: 120 },
        ports: defaultPorts,
        children: [],
        drilldownRef: 'v_hex_api',
      },
      n_comp_domain: {
        id: 'n_comp_domain',
        presetId: 'domain',
        kind: 'domain',
        name: 'OrderDomain',
        tags: ['component'],
        tech: { id: 'domain', label: 'Domain', iconKey: 'component' },
        style: { fillColor: '#6366f1', textColor: '#eef2ff' },
        bounds: { x: 750, y: 130, w: 220, h: 120 },
        ports: defaultPorts,
        children: [],
      },
      n_comp_repo: {
        id: 'n_comp_repo',
        presetId: 'adapter-out',
        kind: 'adapter-out',
        name: 'OrderRepository',
        tags: ['component'],
        tech: { id: 'postgres', label: 'PostgreSQL Adapter', iconKey: 'postgres' },
        style: { fillColor: '#475569', textColor: '#f8fafc' },
        bounds: { x: 430, y: 320, w: 220, h: 100 },
        ports: defaultPorts,
        children: [],
      },
      n_comp_adapter_out: {
        id: 'n_comp_adapter_out',
        presetId: 'adapter-out',
        kind: 'adapter-out',
        name: 'KafkaPublisher',
        tags: ['component'],
        tech: { id: 'kafka', label: 'Kafka Adapter', iconKey: 'kafka' },
        style: { fillColor: '#0f766e', textColor: '#f0fdfa' },
        bounds: { x: 720, y: 320, w: 220, h: 100 },
        ports: defaultPorts,
        children: [],
      },
      n_comp_mapper: {
        id: 'n_comp_mapper',
        presetId: 'component',
        kind: 'component',
        name: 'OrderMapper',
        tags: ['component'],
        tech: { id: 'component', label: 'Mapper', iconKey: 'component' },
        style: { fillColor: '#9333ea', textColor: '#f3e8ff' },
        bounds: { x: 130, y: 320, w: 220, h: 100 },
        ports: defaultPorts,
        children: [],
      },
      n_note_component_guardrails: {
        id: 'n_note_component_guardrails',
        presetId: 'note',
        kind: 'note',
        name: 'Component guardrails:\nservice owns transaction boundary.',
        tags: ['note', 'showcase'],
        bounds: { x: 380, y: 20, w: 290, h: 104 },
        ports: [],
        children: [],
        noteTargetNodeId: 'n_comp_app',
      },
      n_hex_adapter_in: {
        id: 'n_hex_adapter_in',
        presetId: 'adapter-in',
        kind: 'adapter-in',
        name: 'REST Adapter',
        tags: ['hex'],
        tech: { id: 'adapter-in', label: 'REST Controller', iconKey: 'gateway' },
        style: { fillColor: '#2563eb', textColor: '#eff6ff' },
        bounds: { x: 80, y: 170, w: 200, h: 100 },
        ports: defaultPorts,
        children: [],
      },
      n_hex_port_in: {
        id: 'n_hex_port_in',
        presetId: 'port-in',
        kind: 'port-in',
        name: 'CreateOrderPortIn',
        tags: ['hex'],
        tech: { id: 'port-in', label: 'Port In', iconKey: 'gateway' },
        style: { fillColor: '#1d4ed8', textColor: '#dbeafe' },
        bounds: { x: 330, y: 170, w: 200, h: 90 },
        ports: defaultPorts,
        children: [],
      },
      n_hex_app_service: {
        id: 'n_hex_app_service',
        presetId: 'application-service',
        kind: 'application-service',
        name: 'CreateOrderService',
        tags: ['hex'],
        tech: { id: 'application-service', label: 'Application Service', iconKey: 'component' },
        style: { fillColor: '#0891b2', textColor: '#ecfeff' },
        bounds: { x: 580, y: 170, w: 240, h: 110 },
        ports: defaultPorts,
        children: [],
      },
      n_hex_domain: {
        id: 'n_hex_domain',
        presetId: 'domain',
        kind: 'domain',
        name: 'OrderAggregate',
        tags: ['hex'],
        tech: { id: 'domain', label: 'Domain', iconKey: 'component' },
        style: { fillColor: '#6366f1', textColor: '#eef2ff' },
        bounds: { x: 580, y: 320, w: 240, h: 120 },
        ports: defaultPorts,
        children: [],
      },
      n_hex_port_out: {
        id: 'n_hex_port_out',
        presetId: 'port-out',
        kind: 'port-out',
        name: 'PublishOrderPortOut',
        tags: ['hex'],
        tech: { id: 'port-out', label: 'Port Out', iconKey: 'queue' },
        style: { fillColor: '#0f766e', textColor: '#f0fdfa' },
        bounds: { x: 330, y: 340, w: 210, h: 90 },
        ports: defaultPorts,
        children: [],
      },
      n_hex_adapter_out: {
        id: 'n_hex_adapter_out',
        presetId: 'adapter-out',
        kind: 'adapter-out',
        name: 'Kafka Adapter',
        tags: ['hex'],
        tech: { id: 'adapter-out', label: 'Kafka Producer', iconKey: 'kafka' },
        style: { fillColor: '#065f46', textColor: '#d1fae5' },
        bounds: { x: 80, y: 340, w: 210, h: 100 },
        ports: defaultPorts,
        children: [],
      },
      n_hex_obs: {
        id: 'n_hex_obs',
        presetId: 'component',
        kind: 'component',
        name: 'TelemetryAdapter',
        tags: ['hex'],
        tech: { id: 'observability', label: 'Observability', iconKey: 'search' },
        style: { fillColor: '#4338ca', textColor: '#e0e7ff' },
        bounds: { x: 880, y: 250, w: 220, h: 110 },
        ports: defaultPorts,
        children: [],
      },
      n_note_hex_boundary: {
        id: 'n_note_hex_boundary',
        presetId: 'note',
        kind: 'note',
        name: 'Hex boundary:\nports isolate infrastructure adapters.',
        tags: ['note', 'showcase'],
        bounds: { x: 840, y: 70, w: 280, h: 104 },
        ports: [],
        children: [],
        noteTargetNodeId: 'n_hex_app_service',
      },
      n_worker_comp_consumer: {
        id: 'n_worker_comp_consumer',
        presetId: 'adapter-in',
        kind: 'adapter-in',
        name: 'OrderCreatedConsumer',
        tags: ['component'],
        tech: { id: 'adapter-in', label: 'Kafka Consumer', iconKey: 'kafka' },
        style: { fillColor: '#2563eb', textColor: '#eff6ff' },
        bounds: { x: 120, y: 140, w: 240, h: 110 },
        ports: defaultPorts,
        children: [],
      },
      n_worker_comp_app: {
        id: 'n_worker_comp_app',
        presetId: 'application-service',
        kind: 'application-service',
        name: 'ApplyProjectionService',
        tags: ['component'],
        tech: { id: 'application-service', label: 'Application Service', iconKey: 'component' },
        style: { fillColor: '#0f766e', textColor: '#f0fdfa' },
        bounds: { x: 420, y: 130, w: 260, h: 120 },
        ports: defaultPorts,
        children: [],
        drilldownRef: 'v_hex_worker',
      },
      n_worker_comp_projection_repo: {
        id: 'n_worker_comp_projection_repo',
        presetId: 'adapter-out',
        kind: 'adapter-out',
        name: 'ProjectionRepository',
        tags: ['component'],
        tech: { id: 'adapter-out', label: 'Mongo Adapter', iconKey: 'component' },
        style: { fillColor: '#475569', textColor: '#f8fafc' },
        bounds: { x: 750, y: 130, w: 250, h: 110 },
        ports: defaultPorts,
        children: [],
      },
      n_worker_comp_metric_publisher: {
        id: 'n_worker_comp_metric_publisher',
        presetId: 'adapter-out',
        kind: 'adapter-out',
        name: 'MetricPublisher',
        tags: ['component'],
        tech: { id: 'adapter-out', label: 'HTTP Adapter', iconKey: 'search' },
        style: { fillColor: '#7c3aed', textColor: '#f3e8ff' },
        bounds: { x: 750, y: 310, w: 250, h: 100 },
        ports: defaultPorts,
        children: [],
      },
      n_note_worker_flow: {
        id: 'n_note_worker_flow',
        presetId: 'note',
        kind: 'note',
        name: 'Fulfillment flow:\nconsumer validates event, then updates projection and metrics.',
        tags: ['note', 'showcase'],
        bounds: { x: 390, y: 20, w: 320, h: 106 },
        ports: [],
        children: [],
        noteTargetNodeId: 'n_worker_comp_app',
      },
      n_worker_hex_adapter_in: {
        id: 'n_worker_hex_adapter_in',
        presetId: 'adapter-in',
        kind: 'adapter-in',
        name: 'KafkaConsumerAdapter',
        tags: ['hex'],
        tech: { id: 'adapter-in', label: 'Kafka Consumer', iconKey: 'kafka' },
        style: { fillColor: '#2563eb', textColor: '#eff6ff' },
        bounds: { x: 90, y: 170, w: 220, h: 100 },
        ports: defaultPorts,
        children: [],
      },
      n_worker_hex_port_in: {
        id: 'n_worker_hex_port_in',
        presetId: 'port-in',
        kind: 'port-in',
        name: 'ApplyProjectionPortIn',
        tags: ['hex'],
        tech: { id: 'port-in', label: 'Port In', iconKey: 'gateway' },
        style: { fillColor: '#1d4ed8', textColor: '#dbeafe' },
        bounds: { x: 360, y: 170, w: 230, h: 90 },
        ports: defaultPorts,
        children: [],
      },
      n_worker_hex_app_service: {
        id: 'n_worker_hex_app_service',
        presetId: 'application-service',
        kind: 'application-service',
        name: 'ApplyProjectionUseCase',
        tags: ['hex'],
        tech: { id: 'application-service', label: 'Application Service', iconKey: 'component' },
        style: { fillColor: '#0f766e', textColor: '#f0fdfa' },
        bounds: { x: 640, y: 170, w: 260, h: 110 },
        ports: defaultPorts,
        children: [],
      },
      n_worker_hex_domain: {
        id: 'n_worker_hex_domain',
        presetId: 'domain',
        kind: 'domain',
        name: 'FulfillmentProjectionDomain',
        tags: ['hex'],
        tech: { id: 'domain', label: 'Domain', iconKey: 'component' },
        style: { fillColor: '#6366f1', textColor: '#eef2ff' },
        bounds: { x: 640, y: 330, w: 260, h: 120 },
        ports: defaultPorts,
        children: [],
      },
      n_worker_hex_port_out: {
        id: 'n_worker_hex_port_out',
        presetId: 'port-out',
        kind: 'port-out',
        name: 'ProjectionStorePortOut',
        tags: ['hex'],
        tech: { id: 'port-out', label: 'Port Out', iconKey: 'queue' },
        style: { fillColor: '#0d9488', textColor: '#f0fdfa' },
        bounds: { x: 360, y: 350, w: 240, h: 90 },
        ports: defaultPorts,
        children: [],
      },
      n_worker_hex_adapter_out: {
        id: 'n_worker_hex_adapter_out',
        presetId: 'adapter-out',
        kind: 'adapter-out',
        name: 'MongoProjectionAdapter',
        tags: ['hex'],
        tech: { id: 'adapter-out', label: 'MongoDB Adapter', iconKey: 'component' },
        style: { fillColor: '#475569', textColor: '#f8fafc' },
        bounds: { x: 90, y: 350, w: 240, h: 100 },
        ports: defaultPorts,
        children: [],
      },
      n_worker_hex_obs: {
        id: 'n_worker_hex_obs',
        presetId: 'component',
        kind: 'component',
        name: 'TelemetryAdapter',
        tags: ['hex'],
        tech: { id: 'observability', label: 'Observability', iconKey: 'search' },
        style: { fillColor: '#7c3aed', textColor: '#f3e8ff' },
        bounds: { x: 940, y: 260, w: 230, h: 110 },
        ports: defaultPorts,
        children: [],
      },
      n_note_worker_hex: {
        id: 'n_note_worker_hex',
        presetId: 'note',
        kind: 'note',
        name: 'Hex fulfillment:\nports keep use case independent from storage and telemetry adapters.',
        tags: ['note', 'showcase'],
        bounds: { x: 880, y: 72, w: 300, h: 104 },
        ports: [],
        children: [],
        noteTargetNodeId: 'n_worker_hex_app_service',
      },
    },
    edges: {
      e_c_1: {
        id: 'e_c_1',
        from: { nodeId: 'n_frontend' },
        to: { nodeId: 'n_gateway' },
        protocolPresetId: 'http',
        label: 'POST /api/orders',
        route: { kind: 'auto', points: [] },
        style: { arrow: true, dashed: false, thickness: 2 },
      },
      e_c_2: {
        id: 'e_c_2',
        from: { nodeId: 'n_gateway' },
        to: { nodeId: 'n_auth' },
        protocolPresetId: 'oauth2-token',
        label: 'validate token',
        route: { kind: 'auto', points: [] },
        style: { arrow: true, dashed: false, thickness: 2 },
      },
      e_c_3: {
        id: 'e_c_3',
        from: { nodeId: 'n_gateway' },
        to: { nodeId: 'n_api' },
        protocolPresetId: 'http',
        label: 'forward request',
        route: { kind: 'auto', points: [] },
        style: { arrow: true, dashed: false, thickness: 2 },
      },
      e_c_4: {
        id: 'e_c_4',
        from: { nodeId: 'n_api' },
        to: { nodeId: 'n_db' },
        protocolPresetId: 'sql',
        label: 'insert order',
        route: { kind: 'auto', points: [] },
        style: { arrow: true, dashed: false, thickness: 2 },
      },
      e_c_5: {
        id: 'e_c_5',
        from: { nodeId: 'n_api' },
        to: { nodeId: 'n_kafka' },
        protocolPresetId: 'kafka-event',
        label: 'emit order.created',
        route: { kind: 'auto', points: [] },
        style: { arrow: true, dashed: false, thickness: 2 },
      },
      e_c_6: {
        id: 'e_c_6',
        from: { nodeId: 'n_kafka' },
        to: { nodeId: 'n_worker' },
        protocolPresetId: 'kafka-event',
        label: 'consume order.created',
        route: { kind: 'auto', points: [] },
        style: { arrow: true, dashed: true, thickness: 2 },
      },
      e_c_7: {
        id: 'e_c_7',
        from: { nodeId: 'n_worker' },
        to: { nodeId: 'n_db' },
        protocolPresetId: 'sql',
        label: 'update projection',
        route: { kind: 'auto', points: [] },
        style: { arrow: true, dashed: false, thickness: 2 },
      },
      e_c_8: {
        id: 'e_c_8',
        from: { nodeId: 'n_worker' },
        to: { nodeId: 'n_obs' },
        protocolPresetId: 'http',
        label: 'publish metrics',
        route: { kind: 'auto', points: [] },
        style: { arrow: true, dashed: false, thickness: 2 },
      },
      e_c_9: {
        id: 'e_c_9',
        from: { nodeId: 'n_api' },
        to: { nodeId: 'n_obs' },
        protocolPresetId: 'http',
        label: 'trace span',
        route: { kind: 'auto', points: [] },
        style: { arrow: true, dashed: true, thickness: 2 },
      },
      e_c_10: {
        id: 'e_c_10',
        from: { nodeId: 'n_frontend' },
        to: { nodeId: 'n_api' },
        protocolPresetId: 'http',
        label: 'GET /orders/{id}',
        route: { kind: 'auto', points: [] },
        style: { arrow: true, dashed: false, thickness: 2 },
      },
      e_c_11: {
        id: 'e_c_11',
        from: { nodeId: 'n_api' },
        to: { nodeId: 'n_db' },
        protocolPresetId: 'sql',
        label: 'select order',
        route: { kind: 'auto', points: [] },
        style: { arrow: true, dashed: false, thickness: 2 },
      },
      e_comp_1: {
        id: 'e_comp_1',
        from: { nodeId: 'n_comp_controller' },
        to: { nodeId: 'n_comp_app' },
        protocolPresetId: 'http',
        label: 'create_order',
        route: { kind: 'auto', points: [] },
        style: { arrow: true, dashed: false, thickness: 2 },
      },
      e_comp_2: {
        id: 'e_comp_2',
        from: { nodeId: 'n_comp_app' },
        to: { nodeId: 'n_comp_domain' },
        protocolPresetId: 'internal-call',
        label: 'validate_order_rules',
        route: { kind: 'auto', points: [] },
        style: { arrow: true, dashed: false, thickness: 2 },
      },
      e_comp_3: {
        id: 'e_comp_3',
        from: { nodeId: 'n_comp_app' },
        to: { nodeId: 'n_comp_repo' },
        protocolPresetId: 'sql',
        label: 'persist_order_record',
        route: { kind: 'auto', points: [] },
        style: { arrow: true, dashed: false, thickness: 2 },
      },
      e_comp_4: {
        id: 'e_comp_4',
        from: { nodeId: 'n_comp_app' },
        to: { nodeId: 'n_comp_adapter_out' },
        protocolPresetId: 'kafka-event',
        label: 'publish_order_created_event',
        route: { kind: 'auto', points: [] },
        style: { arrow: true, dashed: false, thickness: 2 },
      },
      e_comp_5: {
        id: 'e_comp_5',
        from: { nodeId: 'n_comp_domain' },
        to: { nodeId: 'n_comp_mapper' },
        protocolPresetId: 'internal-call',
        label: 'map_domain_to_response',
        route: { kind: 'auto', points: [] },
        style: { arrow: true, dashed: false, thickness: 2 },
      },
      e_comp_6: {
        id: 'e_comp_6',
        from: { nodeId: 'n_comp_mapper' },
        to: { nodeId: 'n_comp_controller' },
        protocolPresetId: 'internal-call',
        label: 'return_http_response',
        route: { kind: 'auto', points: [] },
        style: { arrow: true, dashed: true, thickness: 2 },
      },
      e_hex_1: {
        id: 'e_hex_1',
        from: { nodeId: 'n_hex_adapter_in' },
        to: { nodeId: 'n_hex_port_in' },
        protocolPresetId: 'http',
        label: 'capture_create_order_request',
        route: { kind: 'auto', points: [] },
        style: { arrow: true, dashed: false, thickness: 2 },
      },
      e_hex_2: {
        id: 'e_hex_2',
        from: { nodeId: 'n_hex_port_in' },
        to: { nodeId: 'n_hex_app_service' },
        protocolPresetId: 'internal-call',
        label: 'invoke_create_order_use_case',
        route: { kind: 'auto', points: [] },
        style: { arrow: true, dashed: false, thickness: 2 },
      },
      e_hex_3: {
        id: 'e_hex_3',
        from: { nodeId: 'n_hex_app_service' },
        to: { nodeId: 'n_hex_domain' },
        protocolPresetId: 'internal-call',
        label: 'execute_domain_policy',
        route: { kind: 'auto', points: [] },
        style: { arrow: true, dashed: false, thickness: 2 },
      },
      e_hex_4: {
        id: 'e_hex_4',
        from: { nodeId: 'n_hex_app_service' },
        to: { nodeId: 'n_hex_port_out' },
        protocolPresetId: 'internal-call',
        label: 'request_event_publication',
        route: { kind: 'auto', points: [] },
        style: { arrow: true, dashed: false, thickness: 2 },
      },
      e_hex_5: {
        id: 'e_hex_5',
        from: { nodeId: 'n_hex_port_out' },
        to: { nodeId: 'n_hex_adapter_out' },
        protocolPresetId: 'kafka-event',
        label: 'write_event_to_kafka',
        route: { kind: 'auto', points: [] },
        style: { arrow: true, dashed: false, thickness: 2 },
      },
      e_hex_6: {
        id: 'e_hex_6',
        from: { nodeId: 'n_hex_adapter_out' },
        to: { nodeId: 'n_hex_obs' },
        protocolPresetId: 'http',
        label: 'emit_telemetry_span',
        route: { kind: 'auto', points: [] },
        style: { arrow: true, dashed: true, thickness: 2 },
      },
      e_worker_comp_1: {
        id: 'e_worker_comp_1',
        from: { nodeId: 'n_worker_comp_consumer' },
        to: { nodeId: 'n_worker_comp_app' },
        protocolPresetId: 'kafka-event',
        label: 'consume_order_created_event',
        route: { kind: 'auto', points: [] },
        style: { arrow: true, dashed: false, thickness: 2 },
      },
      e_worker_comp_2: {
        id: 'e_worker_comp_2',
        from: { nodeId: 'n_worker_comp_app' },
        to: { nodeId: 'n_worker_comp_projection_repo' },
        protocolPresetId: 'internal-call',
        label: 'apply_projection_rules',
        route: { kind: 'auto', points: [] },
        style: { arrow: true, dashed: false, thickness: 2 },
      },
      e_worker_comp_3: {
        id: 'e_worker_comp_3',
        from: { nodeId: 'n_worker_comp_app' },
        to: { nodeId: 'n_worker_comp_metric_publisher' },
        protocolPresetId: 'http',
        label: 'publish_fulfillment_metric',
        route: { kind: 'auto', points: [] },
        style: { arrow: true, dashed: false, thickness: 2 },
      },
      e_worker_comp_4: {
        id: 'e_worker_comp_4',
        from: { nodeId: 'n_worker_comp_projection_repo' },
        to: { nodeId: 'n_worker_comp_metric_publisher' },
        protocolPresetId: 'internal-call',
        label: 'emit_projection_updated_signal',
        route: { kind: 'auto', points: [] },
        style: { arrow: true, dashed: true, thickness: 2 },
      },
      e_worker_hex_1: {
        id: 'e_worker_hex_1',
        from: { nodeId: 'n_worker_hex_adapter_in' },
        to: { nodeId: 'n_worker_hex_port_in' },
        protocolPresetId: 'kafka-event',
        label: 'receive_order_created_event',
        route: { kind: 'auto', points: [] },
        style: { arrow: true, dashed: false, thickness: 2 },
      },
      e_worker_hex_2: {
        id: 'e_worker_hex_2',
        from: { nodeId: 'n_worker_hex_port_in' },
        to: { nodeId: 'n_worker_hex_app_service' },
        protocolPresetId: 'internal-call',
        label: 'invoke_projection_use_case',
        route: { kind: 'auto', points: [] },
        style: { arrow: true, dashed: false, thickness: 2 },
      },
      e_worker_hex_3: {
        id: 'e_worker_hex_3',
        from: { nodeId: 'n_worker_hex_app_service' },
        to: { nodeId: 'n_worker_hex_domain' },
        protocolPresetId: 'internal-call',
        label: 'enforce_projection_policy',
        route: { kind: 'auto', points: [] },
        style: { arrow: true, dashed: false, thickness: 2 },
      },
      e_worker_hex_4: {
        id: 'e_worker_hex_4',
        from: { nodeId: 'n_worker_hex_app_service' },
        to: { nodeId: 'n_worker_hex_port_out' },
        protocolPresetId: 'internal-call',
        label: 'request_projection_persistence',
        route: { kind: 'auto', points: [] },
        style: { arrow: true, dashed: false, thickness: 2 },
      },
      e_worker_hex_5: {
        id: 'e_worker_hex_5',
        from: { nodeId: 'n_worker_hex_port_out' },
        to: { nodeId: 'n_worker_hex_adapter_out' },
        protocolPresetId: 'internal-call',
        label: 'save_read_model_document',
        route: { kind: 'auto', points: [] },
        style: { arrow: true, dashed: false, thickness: 2 },
      },
      e_worker_hex_6: {
        id: 'e_worker_hex_6',
        from: { nodeId: 'n_worker_hex_adapter_out' },
        to: { nodeId: 'n_worker_hex_obs' },
        protocolPresetId: 'http',
        label: 'publish_projection_telemetry',
        route: { kind: 'auto', points: [] },
        style: { arrow: true, dashed: true, thickness: 2 },
      },
    },
    journeys: {
      j_c_1: {
        id: 'j_c_1',
        name: 'Order Creation (Sync + Event)',
        colorKey: '#2563eb',
        steps: [
          { n: 1, edgeId: 'e_c_1' },
          { n: 2, edgeId: 'e_c_2' },
          { n: 3, edgeId: 'e_c_3' },
          { n: 4, edgeId: 'e_c_4' },
          { n: 5, edgeId: 'e_c_5' },
        ],
        player: { loop: true, speedMs: 1800, pauseOnStep: false },
      },
      j_c_2: {
        id: 'j_c_2',
        name: 'Async Projection Update',
        colorKey: '#16a34a',
        steps: [
          { n: 1, edgeId: 'e_c_5' },
          { n: 2, edgeId: 'e_c_6' },
          { n: 3, edgeId: 'e_c_7' },
          { n: 4, edgeId: 'e_c_8' },
        ],
        player: { loop: true, speedMs: 1800, pauseOnStep: false },
      },
      j_c_3: {
        id: 'j_c_3',
        name: 'Order Query',
        colorKey: '#9333ea',
        steps: [
          { n: 1, edgeId: 'e_c_10' },
          { n: 2, edgeId: 'e_c_11' },
        ],
        player: { loop: true, speedMs: 1800, pauseOnStep: false },
      },
      j_comp_1: {
        id: 'j_comp_1',
        name: 'Order Service Component Orchestration',
        colorKey: '#ea580c',
        steps: [
          { n: 1, edgeId: 'e_comp_1' },
          { n: 2, edgeId: 'e_comp_2' },
          { n: 3, edgeId: 'e_comp_3' },
          { n: 4, edgeId: 'e_comp_4' },
          { n: 5, edgeId: 'e_comp_5' },
          { n: 6, edgeId: 'e_comp_6' },
        ],
        player: { loop: true, speedMs: 1800, pauseOnStep: false },
      },
      j_hex_1: {
        id: 'j_hex_1',
        name: 'Order Service Hexagonal Flow',
        colorKey: '#0891b2',
        steps: [
          { n: 1, edgeId: 'e_hex_1' },
          { n: 2, edgeId: 'e_hex_2' },
          { n: 3, edgeId: 'e_hex_3' },
          { n: 4, edgeId: 'e_hex_4' },
          { n: 5, edgeId: 'e_hex_5' },
          { n: 6, edgeId: 'e_hex_6' },
        ],
        player: { loop: true, speedMs: 1800, pauseOnStep: false },
      },
      j_worker_comp_1: {
        id: 'j_worker_comp_1',
        name: 'Fulfillment Component Orchestration',
        colorKey: '#14b8a6',
        steps: [
          { n: 1, edgeId: 'e_worker_comp_1' },
          { n: 2, edgeId: 'e_worker_comp_2' },
          { n: 3, edgeId: 'e_worker_comp_3' },
          { n: 4, edgeId: 'e_worker_comp_4' },
        ],
        player: { loop: true, speedMs: 1800, pauseOnStep: false },
      },
      j_worker_hex_1: {
        id: 'j_worker_hex_1',
        name: 'Fulfillment Hexagonal Flow',
        colorKey: '#8b5cf6',
        steps: [
          { n: 1, edgeId: 'e_worker_hex_1' },
          { n: 2, edgeId: 'e_worker_hex_2' },
          { n: 3, edgeId: 'e_worker_hex_3' },
          { n: 4, edgeId: 'e_worker_hex_4' },
          { n: 5, edgeId: 'e_worker_hex_5' },
          { n: 6, edgeId: 'e_worker_hex_6' },
        ],
        player: { loop: true, speedMs: 1800, pauseOnStep: false },
      },
    },
    settings: {
      grid: true,
      snap: true,
      theme: 'dark',
      journeyFocus: {
        offscopeRenderMode: 'hide',
        layoutMode: 'preserve',
        autoLayoutMode: 'manual',
      },
    },
  })
