import type { WorkspaceModel } from './types'
import { normalizeWorkspaceNodePorts } from './nodePorts'

const defaultPorts = [
  { id: 'north', x: 0.5, y: 0 },
  { id: 'east', x: 1, y: 0.5 },
  { id: 'south', x: 0.5, y: 1 },
  { id: 'west', x: 0, y: 0.5 },
]

export const createDefaultWorkspace = (): WorkspaceModel =>
  normalizeWorkspaceNodePorts({
    schemaVersion: '1.0',
    workspace: {
      id: 'workspace-default',
      name: 'Orders Platform Showcase',
    },
    views: {
    v_container: {
      id: 'v_container',
      kind: 'container',
      name: 'Container View',
      nodeIds: [
        'n_frontend',
        'n_gateway',
        'n_auth',
        'n_api',
        'n_worker',
        'n_kafka',
        'n_db',
        'n_obs',
      ],
      edgeIds: [
        'e_c_1',
        'e_c_2',
        'e_c_3',
        'e_c_4',
        'e_c_5',
        'e_c_6',
        'e_c_7',
        'e_c_8',
        'e_c_9',
        'e_c_10',
        'e_c_11',
      ],
      journeyIds: ['j_c_1', 'j_c_2', 'j_c_3'],
    },
    v_components_api: {
      id: 'v_components_api',
      kind: 'component',
      name: 'ms-orders Components',
      nodeIds: [
        'n_comp_controller',
        'n_comp_app',
        'n_comp_domain',
        'n_comp_repo',
        'n_comp_adapter_out',
        'n_comp_mapper',
      ],
      edgeIds: ['e_comp_1', 'e_comp_2', 'e_comp_3', 'e_comp_4', 'e_comp_5', 'e_comp_6'],
      journeyIds: ['j_comp_1'],
    },
    v_hex_api: {
      id: 'v_hex_api',
      kind: 'hex',
      name: 'ms-orders Hex View',
      nodeIds: [
        'n_hex_adapter_in',
        'n_hex_port_in',
        'n_hex_app_service',
        'n_hex_domain',
        'n_hex_port_out',
        'n_hex_adapter_out',
        'n_hex_obs',
      ],
      edgeIds: ['e_hex_1', 'e_hex_2', 'e_hex_3', 'e_hex_4', 'e_hex_5', 'e_hex_6'],
      journeyIds: ['j_hex_1'],
    },
  },
  nodes: {
    n_frontend: {
      id: 'n_frontend',
      presetId: 'container',
      kind: 'container',
      name: 'web-portal',
      tags: ['entrypoint'],
      tech: { id: 'react', label: 'React', iconKey: 'component' },
      bounds: { x: 70, y: 110, w: 220, h: 120 },
      ports: defaultPorts,
      children: [],
    },
    n_gateway: {
      id: 'n_gateway',
      presetId: 'gateway',
      kind: 'gateway',
      name: 'api-gateway',
      tags: ['infra'],
      tech: { id: 'nginx', label: 'NGINX', iconKey: 'gateway' },
      bounds: { x: 350, y: 110, w: 220, h: 110 },
      ports: defaultPorts,
      children: [],
    },
    n_auth: {
      id: 'n_auth',
      presetId: 'security',
      kind: 'security',
      name: 'auth-service',
      tags: ['security'],
      tech: { id: 'oauth2', label: 'OAuth2', iconKey: 'security' },
      bounds: { x: 350, y: 270, w: 220, h: 100 },
      ports: defaultPorts,
      children: [],
    },
    n_api: {
      id: 'n_api',
      presetId: 'container',
      kind: 'container',
      name: 'ms-orders',
      tags: ['core'],
      tech: { id: 'spring-boot', label: 'Spring Boot', iconKey: 'spring' },
      bounds: { x: 640, y: 110, w: 220, h: 120 },
      ports: defaultPorts,
      children: [],
      drilldownRef: 'v_components_api',
    },
    n_worker: {
      id: 'n_worker',
      presetId: 'container',
      kind: 'container',
      name: 'ms-fulfillment',
      tags: ['core'],
      tech: { id: 'spring-boot', label: 'Spring Boot', iconKey: 'spring' },
      bounds: { x: 640, y: 280, w: 220, h: 120 },
      ports: defaultPorts,
      children: [],
    },
    n_kafka: {
      id: 'n_kafka',
      presetId: 'queue',
      kind: 'queue',
      name: 'Kafka',
      tags: ['infra'],
      tech: { id: 'kafka', label: 'Kafka', iconKey: 'kafka' },
      bounds: { x: 940, y: 100, w: 200, h: 100 },
      ports: defaultPorts,
      children: [],
    },
    n_db: {
      id: 'n_db',
      presetId: 'db',
      kind: 'db',
      name: 'orders-db',
      tags: ['infra'],
      tech: { id: 'postgres', label: 'PostgreSQL', iconKey: 'postgres' },
      bounds: { x: 940, y: 250, w: 200, h: 100 },
      ports: defaultPorts,
      children: [],
    },
    n_obs: {
      id: 'n_obs',
      presetId: 'component',
      kind: 'component',
      name: 'telemetry',
      tags: ['observability'],
      tech: { id: 'observability', label: 'Observability', iconKey: 'search' },
      bounds: { x: 940, y: 410, w: 200, h: 100 },
      ports: defaultPorts,
      children: [],
    },
    n_comp_controller: {
      id: 'n_comp_controller',
      presetId: 'adapter-in',
      kind: 'adapter-in',
      name: 'OrdersController',
      tags: ['component'],
      tech: { id: 'adapter-in', label: 'REST Adapter', iconKey: 'gateway' },
      bounds: { x: 130, y: 140, w: 220, h: 110 },
      ports: defaultPorts,
      children: [],
    },
    n_comp_app: {
      id: 'n_comp_app',
      presetId: 'application-service',
      kind: 'application-service',
      name: 'CreateOrderService',
      tags: ['component'],
      tech: { id: 'application-service', label: 'Application Service', iconKey: 'component' },
      bounds: { x: 430, y: 130, w: 250, h: 120 },
      ports: defaultPorts,
      children: [],
      drilldownRef: 'v_hex_api',
    },
    n_comp_domain: {
      id: 'n_comp_domain',
      presetId: 'domain',
      kind: 'domain',
      name: 'OrderDomain',
      tags: ['component'],
      tech: { id: 'domain', label: 'Domain', iconKey: 'component' },
      bounds: { x: 750, y: 130, w: 220, h: 120 },
      ports: defaultPorts,
      children: [],
    },
    n_comp_repo: {
      id: 'n_comp_repo',
      presetId: 'adapter-out',
      kind: 'adapter-out',
      name: 'OrderRepository',
      tags: ['component'],
      tech: { id: 'postgres', label: 'PostgreSQL Adapter', iconKey: 'postgres' },
      bounds: { x: 430, y: 320, w: 220, h: 100 },
      ports: defaultPorts,
      children: [],
    },
    n_comp_adapter_out: {
      id: 'n_comp_adapter_out',
      presetId: 'adapter-out',
      kind: 'adapter-out',
      name: 'KafkaPublisher',
      tags: ['component'],
      tech: { id: 'kafka', label: 'Kafka Adapter', iconKey: 'kafka' },
      bounds: { x: 720, y: 320, w: 220, h: 100 },
      ports: defaultPorts,
      children: [],
    },
    n_comp_mapper: {
      id: 'n_comp_mapper',
      presetId: 'component',
      kind: 'component',
      name: 'OrderMapper',
      tags: ['component'],
      tech: { id: 'component', label: 'Mapper', iconKey: 'component' },
      bounds: { x: 130, y: 320, w: 220, h: 100 },
      ports: defaultPorts,
      children: [],
    },
    n_hex_adapter_in: {
      id: 'n_hex_adapter_in',
      presetId: 'adapter-in',
      kind: 'adapter-in',
      name: 'REST Adapter',
      tags: ['hex'],
      tech: { id: 'adapter-in', label: 'REST Controller', iconKey: 'gateway' },
      bounds: { x: 80, y: 170, w: 200, h: 100 },
      ports: defaultPorts,
      children: [],
    },
    n_hex_port_in: {
      id: 'n_hex_port_in',
      presetId: 'port-in',
      kind: 'port-in',
      name: 'CreateOrderPortIn',
      tags: ['hex'],
      tech: { id: 'port-in', label: 'Port In', iconKey: 'gateway' },
      bounds: { x: 330, y: 170, w: 200, h: 90 },
      ports: defaultPorts,
      children: [],
    },
    n_hex_app_service: {
      id: 'n_hex_app_service',
      presetId: 'application-service',
      kind: 'application-service',
      name: 'CreateOrderService',
      tags: ['hex'],
      tech: { id: 'application-service', label: 'Application Service', iconKey: 'component' },
      bounds: { x: 580, y: 170, w: 240, h: 110 },
      ports: defaultPorts,
      children: [],
    },
    n_hex_domain: {
      id: 'n_hex_domain',
      presetId: 'domain',
      kind: 'domain',
      name: 'OrderAggregate',
      tags: ['hex'],
      tech: { id: 'domain', label: 'Domain', iconKey: 'component' },
      bounds: { x: 580, y: 320, w: 240, h: 120 },
      ports: defaultPorts,
      children: [],
    },
    n_hex_port_out: {
      id: 'n_hex_port_out',
      presetId: 'port-out',
      kind: 'port-out',
      name: 'PublishOrderPortOut',
      tags: ['hex'],
      tech: { id: 'port-out', label: 'Port Out', iconKey: 'queue' },
      bounds: { x: 330, y: 340, w: 210, h: 90 },
      ports: defaultPorts,
      children: [],
    },
    n_hex_adapter_out: {
      id: 'n_hex_adapter_out',
      presetId: 'adapter-out',
      kind: 'adapter-out',
      name: 'Kafka Adapter',
      tags: ['hex'],
      tech: { id: 'adapter-out', label: 'Kafka Producer', iconKey: 'kafka' },
      bounds: { x: 80, y: 340, w: 210, h: 100 },
      ports: defaultPorts,
      children: [],
    },
    n_hex_obs: {
      id: 'n_hex_obs',
      presetId: 'component',
      kind: 'component',
      name: 'TelemetryAdapter',
      tags: ['hex'],
      tech: { id: 'observability', label: 'Observability', iconKey: 'search' },
      bounds: { x: 880, y: 250, w: 220, h: 110 },
      ports: defaultPorts,
      children: [],
    },
  },
  edges: {
    e_c_1: {
      id: 'e_c_1',
      from: { nodeId: 'n_frontend' },
      to: { nodeId: 'n_gateway' },
      protocolPresetId: 'http',
      label: 'POST /api/orders',
      route: { kind: 'auto', points: [] },
      style: { arrow: true, dashed: false, thickness: 2 },
    },
    e_c_2: {
      id: 'e_c_2',
      from: { nodeId: 'n_gateway' },
      to: { nodeId: 'n_auth' },
      protocolPresetId: 'oauth2-token',
      label: 'validate token',
      route: { kind: 'auto', points: [] },
      style: { arrow: true, dashed: false, thickness: 2 },
    },
    e_c_3: {
      id: 'e_c_3',
      from: { nodeId: 'n_gateway' },
      to: { nodeId: 'n_api' },
      protocolPresetId: 'http',
      label: 'forward request',
      route: { kind: 'auto', points: [] },
      style: { arrow: true, dashed: false, thickness: 2 },
    },
    e_c_4: {
      id: 'e_c_4',
      from: { nodeId: 'n_api' },
      to: { nodeId: 'n_db' },
      protocolPresetId: 'sql',
      label: 'insert order',
      route: { kind: 'auto', points: [] },
      style: { arrow: true, dashed: false, thickness: 2 },
    },
    e_c_5: {
      id: 'e_c_5',
      from: { nodeId: 'n_api' },
      to: { nodeId: 'n_kafka' },
      protocolPresetId: 'kafka-event',
      label: 'emit order.created',
      route: { kind: 'auto', points: [] },
      style: { arrow: true, dashed: false, thickness: 2 },
    },
    e_c_6: {
      id: 'e_c_6',
      from: { nodeId: 'n_kafka' },
      to: { nodeId: 'n_worker' },
      protocolPresetId: 'kafka-event',
      label: 'consume order.created',
      route: { kind: 'auto', points: [] },
      style: { arrow: true, dashed: true, thickness: 2 },
    },
    e_c_7: {
      id: 'e_c_7',
      from: { nodeId: 'n_worker' },
      to: { nodeId: 'n_db' },
      protocolPresetId: 'sql',
      label: 'update projection',
      route: { kind: 'auto', points: [] },
      style: { arrow: true, dashed: false, thickness: 2 },
    },
    e_c_8: {
      id: 'e_c_8',
      from: { nodeId: 'n_worker' },
      to: { nodeId: 'n_obs' },
      protocolPresetId: 'http',
      label: 'publish metrics',
      route: { kind: 'auto', points: [] },
      style: { arrow: true, dashed: false, thickness: 2 },
    },
    e_c_9: {
      id: 'e_c_9',
      from: { nodeId: 'n_api' },
      to: { nodeId: 'n_obs' },
      protocolPresetId: 'http',
      label: 'trace span',
      route: { kind: 'auto', points: [] },
      style: { arrow: true, dashed: true, thickness: 2 },
    },
    e_c_10: {
      id: 'e_c_10',
      from: { nodeId: 'n_frontend' },
      to: { nodeId: 'n_api' },
      protocolPresetId: 'http',
      label: 'GET /orders/{id}',
      route: { kind: 'auto', points: [] },
      style: { arrow: true, dashed: false, thickness: 2 },
    },
    e_c_11: {
      id: 'e_c_11',
      from: { nodeId: 'n_api' },
      to: { nodeId: 'n_db' },
      protocolPresetId: 'sql',
      label: 'select order',
      route: { kind: 'auto', points: [] },
      style: { arrow: true, dashed: false, thickness: 2 },
    },
    e_comp_1: {
      id: 'e_comp_1',
      from: { nodeId: 'n_comp_controller' },
      to: { nodeId: 'n_comp_app' },
      protocolPresetId: 'http',
      label: 'createOrder()',
      route: { kind: 'auto', points: [] },
      style: { arrow: true, dashed: false, thickness: 2 },
    },
    e_comp_2: {
      id: 'e_comp_2',
      from: { nodeId: 'n_comp_app' },
      to: { nodeId: 'n_comp_domain' },
      protocolPresetId: 'internal-call',
      label: 'validateAndBuild()',
      route: { kind: 'auto', points: [] },
      style: { arrow: true, dashed: false, thickness: 2 },
    },
    e_comp_3: {
      id: 'e_comp_3',
      from: { nodeId: 'n_comp_app' },
      to: { nodeId: 'n_comp_repo' },
      protocolPresetId: 'sql',
      label: 'save(order)',
      route: { kind: 'auto', points: [] },
      style: { arrow: true, dashed: false, thickness: 2 },
    },
    e_comp_4: {
      id: 'e_comp_4',
      from: { nodeId: 'n_comp_app' },
      to: { nodeId: 'n_comp_adapter_out' },
      protocolPresetId: 'kafka-event',
      label: 'publish(order.created)',
      route: { kind: 'auto', points: [] },
      style: { arrow: true, dashed: false, thickness: 2 },
    },
    e_comp_5: {
      id: 'e_comp_5',
      from: { nodeId: 'n_comp_domain' },
      to: { nodeId: 'n_comp_mapper' },
      protocolPresetId: 'internal-call',
      label: 'toResponse()',
      route: { kind: 'auto', points: [] },
      style: { arrow: true, dashed: false, thickness: 2 },
    },
    e_comp_6: {
      id: 'e_comp_6',
      from: { nodeId: 'n_comp_mapper' },
      to: { nodeId: 'n_comp_controller' },
      protocolPresetId: 'internal-call',
      label: 'return response',
      route: { kind: 'auto', points: [] },
      style: { arrow: true, dashed: true, thickness: 2 },
    },
    e_hex_1: {
      id: 'e_hex_1',
      from: { nodeId: 'n_hex_adapter_in' },
      to: { nodeId: 'n_hex_port_in' },
      protocolPresetId: 'http',
      label: 'HTTP POST /orders',
      route: { kind: 'auto', points: [] },
      style: { arrow: true, dashed: false, thickness: 2 },
    },
    e_hex_2: {
      id: 'e_hex_2',
      from: { nodeId: 'n_hex_port_in' },
      to: { nodeId: 'n_hex_app_service' },
      protocolPresetId: 'internal-call',
      label: 'invoke use case',
      route: { kind: 'auto', points: [] },
      style: { arrow: true, dashed: false, thickness: 2 },
    },
    e_hex_3: {
      id: 'e_hex_3',
      from: { nodeId: 'n_hex_app_service' },
      to: { nodeId: 'n_hex_domain' },
      protocolPresetId: 'internal-call',
      label: 'domain rules',
      route: { kind: 'auto', points: [] },
      style: { arrow: true, dashed: false, thickness: 2 },
    },
    e_hex_4: {
      id: 'e_hex_4',
      from: { nodeId: 'n_hex_app_service' },
      to: { nodeId: 'n_hex_port_out' },
      protocolPresetId: 'internal-call',
      label: 'emit event',
      route: { kind: 'auto', points: [] },
      style: { arrow: true, dashed: false, thickness: 2 },
    },
    e_hex_5: {
      id: 'e_hex_5',
      from: { nodeId: 'n_hex_port_out' },
      to: { nodeId: 'n_hex_adapter_out' },
      protocolPresetId: 'kafka-event',
      label: 'publish kafka',
      route: { kind: 'auto', points: [] },
      style: { arrow: true, dashed: false, thickness: 2 },
    },
    e_hex_6: {
      id: 'e_hex_6',
      from: { nodeId: 'n_hex_adapter_out' },
      to: { nodeId: 'n_hex_obs' },
      protocolPresetId: 'http',
      label: 'send telemetry',
      route: { kind: 'auto', points: [] },
      style: { arrow: true, dashed: true, thickness: 2 },
    },
  },
  journeys: {
    j_c_1: {
      id: 'j_c_1',
      name: 'Order Creation (Sync + Event)',
      colorKey: '#2563eb',
      steps: [
        { n: 1, edgeId: 'e_c_1' },
        { n: 2, edgeId: 'e_c_2' },
        { n: 3, edgeId: 'e_c_3' },
        { n: 4, edgeId: 'e_c_4' },
        { n: 5, edgeId: 'e_c_5' },
      ],
      player: { loop: true, speedMs: 1800, pauseOnStep: false },
    },
    j_c_2: {
      id: 'j_c_2',
      name: 'Async Projection Update',
      colorKey: '#16a34a',
      steps: [
        { n: 1, edgeId: 'e_c_5' },
        { n: 2, edgeId: 'e_c_6' },
        { n: 3, edgeId: 'e_c_7' },
        { n: 4, edgeId: 'e_c_8' },
      ],
      player: { loop: true, speedMs: 1800, pauseOnStep: false },
    },
    j_c_3: {
      id: 'j_c_3',
      name: 'Order Query',
      colorKey: '#9333ea',
      steps: [
        { n: 1, edgeId: 'e_c_10' },
        { n: 2, edgeId: 'e_c_11' },
      ],
      player: { loop: true, speedMs: 1800, pauseOnStep: false },
    },
    j_comp_1: {
      id: 'j_comp_1',
      name: 'Component Orchestration',
      colorKey: '#ea580c',
      steps: [
        { n: 1, edgeId: 'e_comp_1' },
        { n: 2, edgeId: 'e_comp_2' },
        { n: 3, edgeId: 'e_comp_3' },
        { n: 4, edgeId: 'e_comp_4' },
        { n: 5, edgeId: 'e_comp_5' },
        { n: 6, edgeId: 'e_comp_6' },
      ],
      player: { loop: true, speedMs: 1800, pauseOnStep: false },
    },
    j_hex_1: {
      id: 'j_hex_1',
      name: 'Hex Create Order',
      colorKey: '#0891b2',
      steps: [
        { n: 1, edgeId: 'e_hex_1' },
        { n: 2, edgeId: 'e_hex_2' },
        { n: 3, edgeId: 'e_hex_3' },
        { n: 4, edgeId: 'e_hex_4' },
        { n: 5, edgeId: 'e_hex_5' },
        { n: 6, edgeId: 'e_hex_6' },
      ],
      player: { loop: true, speedMs: 1800, pauseOnStep: false },
    },
  },
  settings: {
    grid: true,
    snap: true,
    theme: 'dark',
    journeyFocus: {
      offscopeRenderMode: 'hide',
      layoutMode: 'preserve',
      autoLayoutMode: 'manual',
    },
  },
  })
